// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWriteOptionalData(w bsatn.Writer, v *OptionalData) {
	w.PutU64(v.Id)
	if v.OptName != nil {
		w.PutSumTag(0) // Some
		w.PutString((*v.OptName))
	} else {
		w.PutSumTag(1) // None
	}
	w.PutArrayLen(uint32(len(v.Tags)))
	for stdbIdx := range v.Tags {
		w.PutString(v.Tags[stdbIdx])
	}
	w.PutArrayLen(uint32(len(v.Scores)))
	for stdbIdx := range v.Scores {
		w.PutI32(v.Scores[stdbIdx])
	}
	bsatn.WriteByteArray(w, v.RawData)
}

func StdbReadOptionalData(r bsatn.Reader, v *OptionalData) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	{
		var tag uint8
		if tag, err = r.GetU8(); err != nil {
			return fmt.Errorf("decode OptName tag: %w", err)
		}
		if tag == 0 {
			var tmpOptName string
			if tmpOptName, err = r.GetString(); err != nil {
				return fmt.Errorf("decode OptName_val: %w", err)
			}
			v.OptName = &tmpOptName
		} else {
			v.OptName = nil
		}
	}
	{
		var arrLen uint32
		if arrLen, err = r.GetArrayLen(); err != nil {
			return fmt.Errorf("decode Tags len: %w", err)
		}
		v.Tags = make([]string, arrLen)
		for stdbIdx := uint32(0); stdbIdx < arrLen; stdbIdx++ {
			if v.Tags[stdbIdx], err = r.GetString(); err != nil {
				return fmt.Errorf("decode Tags_elem: %w", err)
			}
		}
	}
	{
		var arrLen uint32
		if arrLen, err = r.GetArrayLen(); err != nil {
			return fmt.Errorf("decode Scores len: %w", err)
		}
		v.Scores = make([]int32, arrLen)
		for stdbIdx := uint32(0); stdbIdx < arrLen; stdbIdx++ {
			if v.Scores[stdbIdx], err = r.GetI32(); err != nil {
				return fmt.Errorf("decode Scores_elem: %w", err)
			}
		}
	}
	if v.RawData, err = bsatn.ReadByteArray(r); err != nil {
		return fmt.Errorf("decode RawData: %w", err)
	}
	return nil
}

type stdbOptionalDataTableHandle struct {
	tableId  uint32
	resolved bool
}

var OptionalDataTable = &stdbOptionalDataTableHandle{}

func (t *stdbOptionalDataTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("optional_data")
	if err != nil {
		panic(fmt.Sprintf("OptionalDataTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbOptionalDataTableHandle) Insert(row OptionalData) OptionalData {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWriteOptionalData(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("OptionalDataTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbOptionalDataTableHandle) Delete(row OptionalData) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWriteOptionalData(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("OptionalDataTable.Delete: %v", err))
	}
}

func (t *stdbOptionalDataTableHandle) Scan() (runtime.TableIterator[OptionalData], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[OptionalData](iter, func(r bsatn.Reader, v *OptionalData) error {
		return StdbReadOptionalData(r, v)
	}), nil
}

func (t *stdbOptionalDataTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbOptionalDataTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbOptionalDataTableHandle) FindById(key uint64) (OptionalData, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("optional_data_id_idx_btree")
	if err != nil {
		var zero OptionalData
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero OptionalData
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero OptionalData
		return zero, false, err
	}
	var result OptionalData
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadOptionalData(r, &result); err != nil {
		var zero OptionalData
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbOptionalDataTableHandle) UpdateById(row OptionalData) OptionalData {
	t.resolve()
	indexId, err := runtime.GetIndexId("optional_data_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("OptionalDataTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWriteOptionalData(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("OptionalDataTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbOptionalDataTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("optional_data_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("OptionalDataTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("OptionalDataTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refOptionalData := ts.Reserve()

	ts.Set(refOptionalData, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "opt_name", AlgebraicType: types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "some", AlgebraicType: types.AlgTypeString()},
			types.SumTypeVariant{Name: "none", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		))},
		types.ProductTypeElement{Name: "tags", AlgebraicType: types.AlgTypeArray(types.AlgTypeString())},
		types.ProductTypeElement{Name: "scores", AlgebraicType: types.AlgTypeArray(types.AlgTypeI32())},
		types.ProductTypeElement{Name: "raw_data", AlgebraicType: types.AlgTypeArray(types.AlgTypeU8())},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "OptionalData", refOptionalData).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("optional_data").
		WithProductTypeRef(refOptionalData).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("optional_data_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
