// Code generated by stdb-gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/bsatn"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/moduledef"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/reducer"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/runtime"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/sys"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/types"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteEntity(w bsatn.Writer, v *Entity) {
	w.PutU64(v.Id)
	stdbWriteTransform(w, &v.Transform)
}

func stdbReadEntity(r bsatn.Reader, v *Entity) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if err = stdbReadTransform(r, &v.Transform); err != nil {
		return fmt.Errorf("decode Transform: %w", err)
	}
	return nil
}

func stdbWriteTransform(w bsatn.Writer, v *Transform) {
	stdbWriteVector2(w, &v.Position)
	w.PutF32(v.Rotation)
	w.PutF32(v.Scale)
}

func stdbReadTransform(r bsatn.Reader, v *Transform) error {
	var err error
	if err = stdbReadVector2(r, &v.Position); err != nil {
		return fmt.Errorf("decode Position: %w", err)
	}
	if v.Rotation, err = r.GetF32(); err != nil {
		return fmt.Errorf("decode Rotation: %w", err)
	}
	if v.Scale, err = r.GetF32(); err != nil {
		return fmt.Errorf("decode Scale: %w", err)
	}
	return nil
}

func stdbWriteVector2(w bsatn.Writer, v *Vector2) {
	w.PutF64(v.X)
	w.PutF64(v.Y)
}

func stdbReadVector2(r bsatn.Reader, v *Vector2) error {
	var err error
	if v.X, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode X: %w", err)
	}
	if v.Y, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode Y: %w", err)
	}
	return nil
}

type stdbEntityTableHandle struct {
	tableId  uint32
	resolved bool
}

var EntityTable = &stdbEntityTableHandle{}

func (t *stdbEntityTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("entity")
	if err != nil {
		panic(fmt.Sprintf("EntityTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbEntityTableHandle) Insert(row Entity) Entity {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteEntity(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("EntityTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbEntityTableHandle) Delete(row Entity) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteEntity(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("EntityTable.Delete: %v", err))
	}
}

func (t *stdbEntityTableHandle) Scan() (runtime.TableIterator[Entity], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Entity](iter, func(r bsatn.Reader, v *Entity) error {
		return stdbReadEntity(r, v)
	}), nil
}

func (t *stdbEntityTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbEntityTableHandle) FindById(key uint64) (Entity, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("entity_id_idx_btree")
	if err != nil {
		var zero Entity
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Entity
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Entity
		return zero, false, err
	}
	var result Entity
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadEntity(r, &result); err != nil {
		var zero Entity
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbEntityTableHandle) UpdateById(row Entity) Entity {
	t.resolve()
	indexId, err := runtime.GetIndexId("entity_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("EntityTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWriteEntity(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("EntityTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbEntityTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("entity_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("EntityTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("EntityTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refEntity := ts.Reserve()
	refTransform := ts.Reserve()
	refVector2 := ts.Reserve()

	ts.Set(refEntity, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "transform", AlgebraicType: types.AlgTypeRef(refTransform)},
	)))

	ts.Set(refTransform, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "position", AlgebraicType: types.AlgTypeRef(refVector2)},
		types.ProductTypeElement{Name: "rotation", AlgebraicType: types.AlgTypeF32()},
		types.ProductTypeElement{Name: "scale", AlgebraicType: types.AlgTypeF32()},
	)))

	ts.Set(refVector2, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "x", AlgebraicType: types.AlgTypeF64()},
		types.ProductTypeElement{Name: "y", AlgebraicType: types.AlgTypeF64()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Entity", refEntity).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Transform", refTransform).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Vector2", refVector2).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("entity").
		WithProductTypeRef(refEntity).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("entity_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
