// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteIndexed(w bsatn.Writer, v *Indexed) {
	w.PutU64(v.Id)
	w.PutString(v.Name)
	w.PutU32(v.Age)
	w.PutU8(v.Status)
}

func stdbReadIndexed(r bsatn.Reader, v *Indexed) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	if v.Age, err = r.GetU32(); err != nil {
		return fmt.Errorf("decode Age: %w", err)
	}
	if v.Status, err = r.GetU8(); err != nil {
		return fmt.Errorf("decode Status: %w", err)
	}
	return nil
}

type stdbIndexedTableHandle struct {
	tableId  uint32
	resolved bool
}

var IndexedTable = &stdbIndexedTableHandle{}

func (t *stdbIndexedTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("indexed")
	if err != nil {
		panic(fmt.Sprintf("IndexedTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbIndexedTableHandle) Insert(row Indexed) Indexed {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteIndexed(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbIndexedTableHandle) Delete(row Indexed) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteIndexed(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("IndexedTable.Delete: %v", err))
	}
}

func (t *stdbIndexedTableHandle) Scan() (runtime.TableIterator[Indexed], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Indexed](iter, func(r bsatn.Reader, v *Indexed) error {
		return stdbReadIndexed(r, v)
	}), nil
}

func (t *stdbIndexedTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbIndexedTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbIndexedTableHandle) FindById(key uint64) (Indexed, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_id_idx_btree")
	if err != nil {
		var zero Indexed
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Indexed
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Indexed
		return zero, false, err
	}
	var result Indexed
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadIndexed(r, &result); err != nil {
		var zero Indexed
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbIndexedTableHandle) UpdateById(row Indexed) Indexed {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWriteIndexed(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbIndexedTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.DeleteById: %v", err))
	}
	return deleted
}

func (t *stdbIndexedTableHandle) FindByName(key string) (Indexed, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_name_idx_btree")
	if err != nil {
		var zero Indexed
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutString(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Indexed
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Indexed
		return zero, false, err
	}
	var result Indexed
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadIndexed(r, &result); err != nil {
		var zero Indexed
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbIndexedTableHandle) UpdateByName(row Indexed) Indexed {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_name_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.UpdateByName: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWriteIndexed(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.UpdateByName: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbIndexedTableHandle) DeleteByName(key string) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_name_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.DeleteByName: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutString(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.DeleteByName: %v", err))
	}
	return deleted
}

func (t *stdbIndexedTableHandle) FilterByAge(key uint32) (runtime.TableIterator[Indexed], error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_age_idx_btree")
	if err != nil {
		return nil, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU32(key)
	keyBytes := make([]byte, len(runtime.GlobalWriter.Bytes()))
	copy(keyBytes, runtime.GlobalWriter.Bytes())
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, keyBytes)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Indexed](iter, func(r bsatn.Reader, v *Indexed) error {
		return stdbReadIndexed(r, v)
	}), nil
}

func (t *stdbIndexedTableHandle) DeleteByAge(key uint32) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("indexed_age_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.DeleteByAge: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU32(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("IndexedTable.DeleteByAge: %v", err))
	}
	return deleted
}

func (t *stdbIndexedTableHandle) FilterByIdAndName(id uint64, name string) (runtime.TableIterator[Indexed], error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("multi_idx")
	if err != nil {
		return nil, err
	}
	prefixWriter := bsatn.NewWriter(64)
	prefixWriter.PutU64(id)
	prefixBytes := prefixWriter.Bytes()
	numPrefixCols := uint32(1)
	boundWriter := bsatn.NewWriter(16)
	boundWriter.PutU8(0) // Bound::Included
	boundWriter.PutString(name)
	boundBytes := boundWriter.Bytes()
	iter, err := sys.DatastoreIndexScanRangeBSATN(indexId, prefixBytes, numPrefixCols, boundBytes, boundBytes)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Indexed](iter, func(r bsatn.Reader, v *Indexed) error {
		return stdbReadIndexed(r, v)
	}), nil
}

func (t *stdbIndexedTableHandle) FilterById(id uint64) (runtime.TableIterator[Indexed], error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("multi_idx")
	if err != nil {
		return nil, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(id)
	keyBytes := make([]byte, len(runtime.GlobalWriter.Bytes()))
	copy(keyBytes, runtime.GlobalWriter.Bytes())
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, keyBytes)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Indexed](iter, func(r bsatn.Reader, v *Indexed) error {
		return stdbReadIndexed(r, v)
	}), nil
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refIndexed := ts.Reserve()

	ts.Set(refIndexed, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
		types.ProductTypeElement{Name: "age", AlgebraicType: types.AlgTypeU32()},
		types.ProductTypeElement{Name: "status", AlgebraicType: types.AlgTypeU8()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Indexed", refIndexed).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("indexed").
		WithProductTypeRef(refIndexed).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("indexed_id_idx_btree"), 0).Build()).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 1)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("indexed_name_idx_btree"), 1).Build()).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("indexed_age_idx_btree"), 2).Build()).
		WithIndex(moduledef.NewDirectIndexDef(stdbStrPtr("indexed_status_idx_direct"), 3).Build()).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("multi_idx"), 0, 1).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
