// Code generated by stdb-gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/bsatn"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/moduledef"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/reducer"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/runtime"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/sys"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/types"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	case 0: // Init (__init__)
		Init(ctx)
		return nil
	case 1: // OnConnect (__identity_connected__)
		OnConnect(ctx)
		return nil
	case 2: // OnDisconnect (__identity_disconnected__)
		OnDisconnect(ctx)
		return nil
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("__init__").
		WithParams(types.NewProductType()).
		WithVisibility(moduledef.FunctionVisibilityPrivate).
		WithErrReturnType(types.AlgTypeString()).
		Build())
	builder = builder.AddLifecycleReducer(moduledef.NewLifecycleReducerDef(moduledef.LifecycleInit, "__init__"))

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("__identity_connected__").
		WithParams(types.NewProductType()).
		WithVisibility(moduledef.FunctionVisibilityPrivate).
		WithErrReturnType(types.AlgTypeString()).
		Build())
	builder = builder.AddLifecycleReducer(moduledef.NewLifecycleReducerDef(moduledef.LifecycleOnConnect, "__identity_connected__"))

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("__identity_disconnected__").
		WithParams(types.NewProductType()).
		WithVisibility(moduledef.FunctionVisibilityPrivate).
		WithErrReturnType(types.AlgTypeString()).
		Build())
	builder = builder.AddLifecycleReducer(moduledef.NewLifecycleReducerDef(moduledef.LifecycleOnDisconnect, "__identity_disconnected__"))

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
