// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWriteScoreTable(w bsatn.Writer, v *ScoreTable) {
	w.PutU64(v.Id)
}

func StdbReadScoreTable(r bsatn.Reader, v *ScoreTable) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	return nil
}

func StdbWriteScore(w bsatn.Writer, v *Score) {
	w.PutU64(v.Value)
	w.PutString(v.Label)
}

func StdbReadScore(r bsatn.Reader, v *Score) error {
	var err error
	if v.Value, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Value: %w", err)
	}
	if v.Label, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Label: %w", err)
	}
	return nil
}

type stdbScoresTableHandle struct {
	tableId  uint32
	resolved bool
}

var ScoresTable = &stdbScoresTableHandle{}

func (t *stdbScoresTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("scores")
	if err != nil {
		panic(fmt.Sprintf("ScoresTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbScoresTableHandle) Insert(row ScoreTable) ScoreTable {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWriteScoreTable(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ScoresTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbScoresTableHandle) Delete(row ScoreTable) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWriteScoreTable(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("ScoresTable.Delete: %v", err))
	}
}

func (t *stdbScoresTableHandle) Scan() (runtime.TableIterator[ScoreTable], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[ScoreTable](iter, func(r bsatn.Reader, v *ScoreTable) error {
		return StdbReadScoreTable(r, v)
	}), nil
}

func (t *stdbScoresTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbScoresTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbScoresTableHandle) FindById(key uint64) (ScoreTable, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("scores_id_idx_btree")
	if err != nil {
		var zero ScoreTable
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero ScoreTable
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero ScoreTable
		return zero, false, err
	}
	var result ScoreTable
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadScoreTable(r, &result); err != nil {
		var zero ScoreTable
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbScoresTableHandle) UpdateById(row ScoreTable) ScoreTable {
	t.resolve()
	indexId, err := runtime.GetIndexId("scores_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("ScoresTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWriteScoreTable(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ScoresTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbScoresTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("scores_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("ScoresTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ScoresTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	case 0: // add_score
		stdbReader := bsatn.NewZeroCopyReader(args)
		var score ScoreAlias
		if err := StdbReadScore(stdbReader, &score); err != nil {
			return fmt.Errorf("decode arg 0: %w", err)
		}
		AddScore(ctx, score)
		return nil
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refScoreTable := ts.Reserve()
	refScore := ts.Reserve()

	ts.Set(refScoreTable, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
	)))

	ts.Set(refScore, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "value", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "label", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "ScoreTable", refScoreTable).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Score", refScore).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("scores").
		WithProductTypeRef(refScoreTable).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("scores_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("add_score").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "score", AlgebraicType: types.AlgTypeRef(refScore)},
		)).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
