// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWritePlayer(w bsatn.Writer, v *Player) {
	w.PutU64(v.Id)
	w.PutString(v.Name)
}

func stdbReadPlayer(r bsatn.Reader, v *Player) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	return nil
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbCallProcedure(id uint32, ctx reducer.ProcedureContext, args []byte) ([]byte, error) {
	switch id {
	case 0: // get_player_count
		result := GetPlayerCount(ctx)
		w := bsatn.NewWriter(256)
		w.PutU64(result)
		return w.Bytes(), nil
	case 1: // find_player
		stdbReader := bsatn.NewZeroCopyReader(args)
		var name string
		{
			v, err := stdbReader.GetString()
			if err != nil {
				return nil, fmt.Errorf("decode arg 0: %w", err)
			}
			name = v
		}
		result := FindPlayer(ctx, name)
		w := bsatn.NewWriter(256)
		if result != nil {
			w.PutSumTag(0) // Some
			stdbWritePlayer(w, &(*result))
		} else {
			w.PutSumTag(1) // None
		}
		return w.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown procedure id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refPlayer := ts.Reserve()

	ts.Set(refPlayer, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Player", refPlayer).
		WithCustomOrdering(true).Build())

	builder = builder.AddProcedure(moduledef.NewProcedureDefBuilder("get_player_count").
		WithParams(types.NewProductType()).
		WithReturnType(types.AlgTypeU64()).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		Build())

	builder = builder.AddProcedure(moduledef.NewProcedureDefBuilder("find_player").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
		)).
		WithReturnType(types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "some", AlgebraicType: types.AlgTypeRef(refPlayer)},
			types.SumTypeVariant{Name: "none", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		))).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
	runtime.SetCallProcedureHandler(stdbCallProcedure)
}
