package clientgen

import (
	"fmt"
	"sort"
	"strings"
	"unicode"
)

// toGoName converts a snake_case name to PascalCase for Go.
func toGoName(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		// Handle common acronyms
		upper := strings.ToUpper(part)
		if isCommonAcronym(upper) {
			b.WriteString(upper)
		} else {
			runes := []rune(part)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

// toLowerCamel converts a snake_case name to lowerCamelCase.
func toLowerCamel(s string) string {
	name := toGoName(s)
	if name == "" {
		return ""
	}
	runes := []rune(name)

	// Find the end of leading uppercase sequence
	i := 0
	for i < len(runes) && unicode.IsUpper(runes[i]) {
		i++
	}

	if i == 0 {
		return name
	}

	// If entire string is uppercase, lowercase all
	if i == len(runes) {
		return strings.ToLower(name)
	}

	// If multiple leading uppercase, lowercase all but the last
	if i > 1 {
		for j := 0; j < i-1; j++ {
			runes[j] = unicode.ToLower(runes[j])
		}
	} else {
		runes[0] = unicode.ToLower(runes[0])
	}

	return string(runes)
}

func isCommonAcronym(s string) bool {
	switch s {
	case "ID", "URL", "URI", "HTTP", "HTTPS", "API", "SQL", "JSON", "XML",
		"HTML", "CSS", "JS", "PK", "FK", "DB", "IP", "TCP", "UDP", "RPC",
		"UUID", "BSATN":
		return true
	}
	return false
}

// clientFileHeader returns the standard generated file header for client code.
func clientFileHeader(pkgName string) string {
	return fmt.Sprintf(`// Code generated by stdb-go generate client; DO NOT EDIT.

package %s

`, pkgName)
}

// clientImportBlock builds an import block from unique paths.
func clientImportBlock(imports map[string]string) string {
	if len(imports) == 0 {
		return ""
	}

	type entry struct {
		alias, path string
	}
	entries := make([]entry, 0, len(imports))
	for alias, path := range imports {
		entries = append(entries, entry{alias, path})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].path < entries[j].path
	})

	var b strings.Builder
	b.WriteString("import (\n")
	for _, e := range entries {
		if e.alias != "" && e.alias != pathToAlias(e.path) {
			fmt.Fprintf(&b, "\t%s %q\n", e.alias, e.path)
		} else {
			fmt.Fprintf(&b, "\t%q\n", e.path)
		}
	}
	b.WriteString(")\n\n")
	return b.String()
}

func pathToAlias(path string) string {
	parts := strings.Split(path, "/")
	return parts[len(parts)-1]
}

// goTypeForAlgebraic returns the Go type string for an algebraic type.
func goTypeForAlgebraic(at *AlgebraicType, typespace []AlgebraicType, types []TypeSchema) string {
	switch at.Kind {
	case ATKBuiltin:
		return goTypeForBuiltin(at.Builtin)
	case ATKRef:
		return goTypeForRef(at.Ref, typespace, types)
	case ATKProduct:
		return goTypeForProduct(at.Product, typespace, types)
	case ATKSum:
		return goTypeForSum(at.Sum, typespace, types)
	case ATKArray:
		if at.ArrayTy.Kind == ATKBuiltin && at.ArrayTy.Builtin == BuiltinU8 {
			return "[]byte"
		}
		return "[]" + goTypeForAlgebraic(at.ArrayTy, typespace, types)
	case ATKMap:
		keyType := goTypeForAlgebraic(at.MapKey, typespace, types)
		valType := goTypeForAlgebraic(at.MapValue, typespace, types)
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	default:
		return "any"
	}
}

func goTypeForBuiltin(bt BuiltinType) string {
	switch bt {
	case BuiltinBool:
		return "bool"
	case BuiltinU8:
		return "uint8"
	case BuiltinU16:
		return "uint16"
	case BuiltinU32:
		return "uint32"
	case BuiltinU64:
		return "uint64"
	case BuiltinU128:
		return "types.U128"
	case BuiltinU256:
		return "types.U256"
	case BuiltinI8:
		return "int8"
	case BuiltinI16:
		return "int16"
	case BuiltinI32:
		return "int32"
	case BuiltinI64:
		return "int64"
	case BuiltinI128:
		return "types.I128"
	case BuiltinI256:
		return "types.I256"
	case BuiltinF32:
		return "float32"
	case BuiltinF64:
		return "float64"
	case BuiltinString:
		return "string"
	case BuiltinBytes:
		return "[]byte"
	default:
		return "any"
	}
}

func goTypeForRef(ref int, typespace []AlgebraicType, types []TypeSchema) string {
	// Look up the type name from the named types
	for _, t := range types {
		if t.TypeRef == ref {
			return toGoName(t.Name)
		}
	}

	// If no named type, check if it's a special type
	if ref >= 0 && ref < len(typespace) {
		at := &typespace[ref]
		if at.Kind == ATKProduct {
			if specialType := detectSpecialType(at.Product); specialType != "" {
				return specialType
			}
		}
	}

	// Fall back to inline type
	if ref >= 0 && ref < len(typespace) {
		return goTypeForAlgebraic(&typespace[ref], typespace, types)
	}

	return "any"
}

func goTypeForProduct(pt *ProductType, typespace []AlgebraicType, types []TypeSchema) string {
	// Check for special types first
	if specialType := detectSpecialType(pt); specialType != "" {
		return specialType
	}

	// Check for Option (sum type pattern with some/none)
	// Products with elements are anonymous structs
	if len(pt.Elements) == 0 {
		return "struct{}"
	}

	return "any"
}

func goTypeForSum(st *SumType, typespace []AlgebraicType, types []TypeSchema) string {
	// Check for Option<T>
	if isOptionType(st) {
		someType := goTypeForAlgebraic(&st.Variants[0].AlgebraicType, typespace, types)
		return "*" + someType
	}

	// Check for ScheduleAt
	if isScheduleAtType(st) {
		return "types.ScheduleAt"
	}

	return "any"
}

// detectSpecialType checks if a product type matches a known special type pattern.
func detectSpecialType(pt *ProductType) string {
	if len(pt.Elements) != 1 {
		return ""
	}

	elem := pt.Elements[0]
	switch elem.Name {
	case IdentityTag:
		if elem.AlgebraicType.Kind == ATKBuiltin && elem.AlgebraicType.Builtin == BuiltinU256 {
			return "types.Identity"
		}
	case ConnectionIDTag:
		if elem.AlgebraicType.Kind == ATKBuiltin && elem.AlgebraicType.Builtin == BuiltinU128 {
			return "types.ConnectionId"
		}
	case TimestampTag:
		if elem.AlgebraicType.Kind == ATKBuiltin && elem.AlgebraicType.Builtin == BuiltinI64 {
			return "types.Timestamp"
		}
	case TimeDurationTag:
		if elem.AlgebraicType.Kind == ATKBuiltin && elem.AlgebraicType.Builtin == BuiltinI64 {
			return "types.TimeDuration"
		}
	case UUIDTag:
		if elem.AlgebraicType.Kind == ATKBuiltin && elem.AlgebraicType.Builtin == BuiltinU128 {
			return "types.UUID"
		}
	}

	return ""
}

// isOptionType checks if a sum type is Option<T> (variants: "some" and "none").
func isOptionType(st *SumType) bool {
	if len(st.Variants) != 2 {
		return false
	}
	return (st.Variants[0].Name == "some" && st.Variants[1].Name == "none") ||
		(st.Variants[0].Name == "Some" && st.Variants[1].Name == "None")
}

// isScheduleAtType checks if a sum type is ScheduleAt (variants: "Interval" and "Time").
func isScheduleAtType(st *SumType) bool {
	if len(st.Variants) != 2 {
		return false
	}
	hasInterval := false
	hasTime := false
	for _, v := range st.Variants {
		if v.Name == ScheduleAtIntervalTag {
			hasInterval = true
		}
		if v.Name == ScheduleAtTimeTag {
			hasTime = true
		}
	}
	return hasInterval && hasTime
}

// needsTypesImport returns true if the type string references the types package.
func needsTypesImport(typeStr string) bool {
	return strings.HasPrefix(typeStr, "types.")
}
