package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"go.digitalxero.dev/stdb-go/internal/clientgen"
)

func TestRemoveStaleClientFiles(t *testing.T) {
	dir := t.TempDir()
	generated := "// Code generated by stdb-go generate client; DO NOT EDIT.\n\npackage bindings\n"
	for name, content := range map[string]string{
		"types_generated.go":    generated,
		"bsatn_generated.go":    generated,
		"reducers_generated.go": generated,
		"tables_generated.go":   "package bindings\n// User-maintained code.\n",
		"other_generated.go":    "// Code generated by another tool; DO NOT EDIT.\n",
	} {
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0644))
	}
	require.NoError(t, removeStaleClientFiles(dir, []clientgen.OutputFile{{Name: "types_generated.go"}}))
	for _, name := range []string{"bsatn_generated.go", "reducers_generated.go"} {
		_, err := os.Stat(filepath.Join(dir, name))
		assert.ErrorIs(t, err, os.ErrNotExist)
	}
	for _, name := range []string{"types_generated.go", "tables_generated.go", "other_generated.go"} {
		assert.FileExists(t, filepath.Join(dir, name))
	}

	// A module with only server handlers produces no client files.
	require.NoError(t, removeStaleClientFiles(dir, nil))
	_, err := os.Stat(filepath.Join(dir, "types_generated.go"))
	assert.ErrorIs(t, err, os.ErrNotExist)
	assert.FileExists(t, filepath.Join(dir, "tables_generated.go"))
}
