// Code generated by stdb-gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/bsatn"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/moduledef"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/reducer"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/runtime"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/sys"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/types"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteColor(w bsatn.Writer, v *Color) {
	w.PutU8(uint8(*v))
}

func stdbReadColor(r bsatn.Reader, v *Color) error {
	tag, err := r.GetU8()
	if err != nil {
		return fmt.Errorf("decode Color: %w", err)
	}
	if int(tag) >= 3 {
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "Color"}
	}
	*v = Color(tag)
	return nil
}

func stdbWriteDirection(w bsatn.Writer, v *Direction) {
	w.PutU8(uint8(*v))
}

func stdbReadDirection(r bsatn.Reader, v *Direction) error {
	tag, err := r.GetU8()
	if err != nil {
		return fmt.Errorf("decode Direction: %w", err)
	}
	if int(tag) >= 4 {
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "Direction"}
	}
	*v = Direction(tag)
	return nil
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refColor := ts.Reserve()
	refDirection := ts.Reserve()

	ts.Set(refColor, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Red", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Green", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Blue", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
	)))

	ts.Set(refDirection, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Up", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Down", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Left", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Right", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Color", refColor).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder([]string{"Game"}, "Direction", refDirection).
		WithCustomOrdering(true).Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
