// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// userTableDef implements cache.TypedTableDef for the User table.
type userTableDef struct{}

func (userTableDef) TableName() string { return "User" }

func (userTableDef) DecodeRow(r bsatn.Reader) (*User, error) {
	return ReadUser(r)
}

func (userTableDef) EncodeRow(row *User) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (userTableDef) PrimaryKey(row *User) uint64 {
	return row.ID
}

// UserTable is a type-safe table cache for User rows.
type UserTable = cache.TypedTableCache[*User]
