// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type getUserArgs struct {
	UserID uint64
}

func (a *getUserArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.UserID)
}

// CallGetUser calls the get_user procedure on the server.
func CallGetUser(conn client.DbConnection, userID uint64) error {
	args := &getUserArgs{
		UserID: userID,
	}
	return conn.CallReducer("get_user", args)
}

type searchUsersArgs struct {
	Query string
	Limit uint32
}

func (a *searchUsersArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Query)
	w.PutU32(a.Limit)
}

// CallSearchUsers calls the search_users procedure on the server.
func CallSearchUsers(conn client.DbConnection, query string, limit uint32) error {
	args := &searchUsersArgs{
		Query: query,
		Limit: limit,
	}
	return conn.CallReducer("search_users", args)
}
