// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"context"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type getUserArgs struct {
	UserID uint64
}

func (a *getUserArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.UserID)
}

// CallGetUser calls the get_user procedure on the server.
func CallGetUser(ctx context.Context, conn client.DbConnection, userID uint64) (User, error) {
	var zero User
	args := &getUserArgs{
		UserID: userID,
	}
	raw, err := conn.CallProcedure(ctx, "get_user", args)
	if err != nil {
		return zero, err
	}
	result, err := readGetUserResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readGetUserResult(r bsatn.Reader) (*User, error) {
	var result User
	var err error
	{
		var decoded *User
		decoded, err = ReadUser(r)
		if err != nil {
			return nil, err
		}
		result = *decoded
	}
	_ = err
	return &result, nil
}

type searchUsersArgs struct {
	Query string
	Limit uint32
}

func (a *searchUsersArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Query)
	w.PutU32(a.Limit)
}

// CallSearchUsers calls the search_users procedure on the server.
func CallSearchUsers(ctx context.Context, conn client.DbConnection, query string, limit uint32) ([]User, error) {
	var zero []User
	args := &searchUsersArgs{
		Query: query,
		Limit: limit,
	}
	raw, err := conn.CallProcedure(ctx, "search_users", args)
	if err != nil {
		return zero, err
	}
	result, err := readSearchUsersResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readSearchUsersResult(r bsatn.Reader) (*[]User, error) {
	var result []User
	var err error
	{
		var arrLen uint32
		arrLen, err = r.GetArrayLen()
		if err != nil {
			return nil, err
		}
		result = make([]User, arrLen)
		for i := uint32(0); i < arrLen; i++ {
			{
				var decoded *User
				decoded, err = ReadUser(r)
				if err != nil {
					return nil, err
				}
				result[i] = *decoded
			}
		}
	}
	_ = err
	return &result, nil
}
