// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// playerTableDef implements cache.TypedTableDef for the Player table.
type playerTableDef struct{}

func (playerTableDef) TableName() string { return "Player" }

func (playerTableDef) DecodeRow(r bsatn.Reader) (*Player, error) {
	return ReadPlayer(r)
}

func (playerTableDef) EncodeRow(row *Player) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (playerTableDef) PrimaryKey(row *Player) uint64 {
	return row.ID
}

// PlayerTable is a type-safe table cache for Player rows.
type PlayerTable = cache.TypedTableCache[*Player]
