// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *Player) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutString(v.Name)
	w.PutU32(v.Score)
}

func ReadPlayer(r bsatn.Reader) (*Player, error) {
	v := &Player{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Name, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Score, err = r.GetU32()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v PlayerStatus) WriteBsatn(w bsatn.Writer) {
	w.PutU8(uint8(v))
}

func ReadPlayerStatus(r bsatn.Reader) (PlayerStatus, error) {
	tag, err := r.GetU8()
	if err != nil {
		return 0, err
	}
	return PlayerStatus(tag), nil
}
