// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

type Player struct {
	ID    uint64
	Name  string
	Score uint32
}

type PlayerStatus uint8

const (
	PlayerStatusOnline PlayerStatus = iota
	PlayerStatusOffline
	PlayerStatusAway
)

func (e PlayerStatus) String() string {
	switch e {
	case PlayerStatusOnline:
		return "Online"
	case PlayerStatusOffline:
		return "Offline"
	case PlayerStatusAway:
		return "Away"
	default:
		return "unknown"
	}
}
