// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type addPlayerArgs struct {
	Name  string
	Score uint32
}

func (a *addPlayerArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Name)
	w.PutU32(a.Score)
}

// CallAddPlayer calls the add_player reducer on the server.
func CallAddPlayer(conn client.DbConnection, name string, score uint32) error {
	args := &addPlayerArgs{
		Name:  name,
		Score: score,
	}
	return conn.CallReducer("add_player", args)
}

type updateScoreArgs struct {
	PlayerID uint64
	NewScore uint32
}

func (a *updateScoreArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.PlayerID)
	w.PutU32(a.NewScore)
}

// CallUpdateScore calls the update_score reducer on the server.
func CallUpdateScore(conn client.DbConnection, playerID uint64, newScore uint32) error {
	args := &updateScoreArgs{
		PlayerID: playerID,
		NewScore: newScore,
	}
	return conn.CallReducer("update_score", args)
}
