// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteGameEvent(w bsatn.Writer, v *GameEvent) {
	w.PutU8(v.EventType)
	w.PutString(v.Data)
}

func stdbReadGameEvent(r bsatn.Reader, v *GameEvent) error {
	var err error
	if v.EventType, err = r.GetU8(); err != nil {
		return fmt.Errorf("decode EventType: %w", err)
	}
	if v.Data, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Data: %w", err)
	}
	return nil
}

type stdbGameEventTableHandle struct {
	tableId  uint32
	resolved bool
}

var GameEventTable = &stdbGameEventTableHandle{}

func (t *stdbGameEventTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("game_event")
	if err != nil {
		panic(fmt.Sprintf("GameEventTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbGameEventTableHandle) Insert(row GameEvent) GameEvent {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteGameEvent(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("GameEventTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbGameEventTableHandle) Delete(row GameEvent) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteGameEvent(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("GameEventTable.Delete: %v", err))
	}
}

func (t *stdbGameEventTableHandle) Scan() (runtime.TableIterator[GameEvent], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[GameEvent](iter, func(r bsatn.Reader, v *GameEvent) error {
		return stdbReadGameEvent(r, v)
	}), nil
}

func (t *stdbGameEventTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refGameEvent := ts.Reserve()

	ts.Set(refGameEvent, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "event_type", AlgebraicType: types.AlgTypeU8()},
		types.ProductTypeElement{Name: "data", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "GameEvent", refGameEvent).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("game_event").
		WithProductTypeRef(refGameEvent).
		WithTableAccess(moduledef.TableAccessPublic).
		WithIsEvent(true).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
