// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/types"
)

type AllBuiltins struct {
	FBool   bool
	FU8     uint8
	FU16    uint16
	FU32    uint32
	FU64    uint64
	FU128   types.U128
	FU256   types.U256
	FI8     int8
	FI16    int16
	FI32    int32
	FI64    int64
	FI128   types.I128
	FI256   types.I256
	FF32    float32
	FF64    float64
	FString string
	FBytes  []byte
}
