// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// allBuiltinsTableDef implements cache.TypedTableDef for the AllBuiltins table.
type allBuiltinsTableDef struct{}

func (allBuiltinsTableDef) TableName() string { return "AllBuiltins" }

func (allBuiltinsTableDef) DecodeRow(r bsatn.Reader) (*AllBuiltins, error) {
	return ReadAllBuiltins(r)
}

func (allBuiltinsTableDef) EncodeRow(row *AllBuiltins) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (allBuiltinsTableDef) PrimaryKey(row *AllBuiltins) bool {
	return row.FBool
}

// AllBuiltinsTable is a type-safe table cache for AllBuiltins rows.
type AllBuiltinsTable = cache.TypedTableCache[*AllBuiltins]
