// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *AllBuiltins) WriteBsatn(w bsatn.Writer) {
	w.PutBool(v.FBool)
	w.PutU8(v.FU8)
	w.PutU16(v.FU16)
	w.PutU32(v.FU32)
	w.PutU64(v.FU64)
	v.FU128.WriteBsatn(w)
	v.FU256.WriteBsatn(w)
	w.PutI8(v.FI8)
	w.PutI16(v.FI16)
	w.PutI32(v.FI32)
	w.PutI64(v.FI64)
	v.FI128.WriteBsatn(w)
	v.FI256.WriteBsatn(w)
	w.PutF32(v.FF32)
	w.PutF64(v.FF64)
	w.PutString(v.FString)
	bsatn.WriteByteArray(w, v.FBytes)
}

func ReadAllBuiltins(r bsatn.Reader) (*AllBuiltins, error) {
	v := &AllBuiltins{}
	var err error
	v.FBool, err = r.GetBool()
	if err != nil {
		return nil, err
	}
	v.FU8, err = r.GetU8()
	if err != nil {
		return nil, err
	}
	v.FU16, err = r.GetU16()
	if err != nil {
		return nil, err
	}
	v.FU32, err = r.GetU32()
	if err != nil {
		return nil, err
	}
	v.FU64, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.FU128, err = types.ReadU128(r)
	if err != nil {
		return nil, err
	}
	v.FU256, err = types.ReadU256(r)
	if err != nil {
		return nil, err
	}
	v.FI8, err = r.GetI8()
	if err != nil {
		return nil, err
	}
	v.FI16, err = r.GetI16()
	if err != nil {
		return nil, err
	}
	v.FI32, err = r.GetI32()
	if err != nil {
		return nil, err
	}
	v.FI64, err = r.GetI64()
	if err != nil {
		return nil, err
	}
	v.FI128, err = types.ReadI128(r)
	if err != nil {
		return nil, err
	}
	v.FI256, err = types.ReadI256(r)
	if err != nil {
		return nil, err
	}
	v.FF32, err = r.GetF32()
	if err != nil {
		return nil, err
	}
	v.FF64, err = r.GetF64()
	if err != nil {
		return nil, err
	}
	v.FString, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.FBytes, err = bsatn.ReadByteArray(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}
