// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteStatus(w bsatn.Writer, v *Status) {
	w.PutU8(uint8(*v))
}

func stdbReadStatus(r bsatn.Reader, v *Status) error {
	tag, err := r.GetU8()
	if err != nil {
		return fmt.Errorf("decode Status: %w", err)
	}
	if int(tag) >= 3 {
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "Status"}
	}
	*v = Status(tag)
	return nil
}

func stdbWritePlayer(w bsatn.Writer, v *Player) {
	w.PutU64(v.Id)
	w.PutString(v.Name)
	{
		b := v.Owner.Bytes()
		w.PutBytes(b[:])
	}
	stdbWritePosition(w, &v.Position)
	stdbWriteStatus(w, &v.Status)
	if v.Score != nil {
		w.PutSumTag(0) // Some
		w.PutU64((*v.Score))
	} else {
		w.PutSumTag(1) // None
	}
}

func stdbReadPlayer(r bsatn.Reader, v *Player) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	{
		var tmp types.Identity
		if tmp, err = types.ReadIdentity(r); err != nil {
			return fmt.Errorf("decode Owner: %w", err)
		}
		v.Owner = tmp
	}
	if err = stdbReadPosition(r, &v.Position); err != nil {
		return fmt.Errorf("decode Position: %w", err)
	}
	if err = stdbReadStatus(r, &v.Status); err != nil {
		return fmt.Errorf("decode Status: %w", err)
	}
	{
		var tag uint8
		if tag, err = r.GetU8(); err != nil {
			return fmt.Errorf("decode Score tag: %w", err)
		}
		if tag == 0 {
			var tmpScore uint64
			if tmpScore, err = r.GetU64(); err != nil {
				return fmt.Errorf("decode Score_val: %w", err)
			}
			v.Score = &tmpScore
		} else {
			v.Score = nil
		}
	}
	return nil
}

func stdbWritePosition(w bsatn.Writer, v *Position) {
	w.PutF64(v.X)
	w.PutF64(v.Y)
}

func stdbReadPosition(r bsatn.Reader, v *Position) error {
	var err error
	if v.X, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode X: %w", err)
	}
	if v.Y, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode Y: %w", err)
	}
	return nil
}

func stdbWriteGameLog(w bsatn.Writer, v *GameLog) {
	w.PutString(v.Message)
	w.PutU8(v.Level)
}

func stdbReadGameLog(r bsatn.Reader, v *GameLog) error {
	var err error
	if v.Message, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Message: %w", err)
	}
	if v.Level, err = r.GetU8(); err != nil {
		return fmt.Errorf("decode Level: %w", err)
	}
	return nil
}

type stdbPlayerTableHandle struct {
	tableId  uint32
	resolved bool
}

var PlayerTable = &stdbPlayerTableHandle{}

func (t *stdbPlayerTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("player")
	if err != nil {
		panic(fmt.Sprintf("PlayerTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbPlayerTableHandle) Insert(row Player) Player {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWritePlayer(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.Insert: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbPlayerTableHandle) Delete(row Player) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWritePlayer(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("PlayerTable.Delete: %v", err))
	}
}

func (t *stdbPlayerTableHandle) Scan() (runtime.TableIterator[Player], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Player](iter, func(r bsatn.Reader, v *Player) error {
		return stdbReadPlayer(r, v)
	}), nil
}

func (t *stdbPlayerTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbPlayerTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbPlayerTableHandle) FindById(key uint64) (Player, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("player_id_idx_btree")
	if err != nil {
		var zero Player
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Player
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Player
		return zero, false, err
	}
	var result Player
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadPlayer(r, &result); err != nil {
		var zero Player
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbPlayerTableHandle) UpdateById(row Player) Player {
	t.resolve()
	indexId, err := runtime.GetIndexId("player_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWritePlayer(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.UpdateById: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbPlayerTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("player_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.DeleteById: %v", err))
	}
	return deleted
}

func (t *stdbPlayerTableHandle) FindByName(key string) (Player, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("player_name_idx_btree")
	if err != nil {
		var zero Player
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutString(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Player
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Player
		return zero, false, err
	}
	var result Player
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadPlayer(r, &result); err != nil {
		var zero Player
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbPlayerTableHandle) UpdateByName(row Player) Player {
	t.resolve()
	indexId, err := runtime.GetIndexId("player_name_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.UpdateByName: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWritePlayer(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.UpdateByName: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbPlayerTableHandle) DeleteByName(key string) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("player_name_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.DeleteByName: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutString(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PlayerTable.DeleteByName: %v", err))
	}
	return deleted
}

type stdbGameLogTableHandle struct {
	tableId  uint32
	resolved bool
}

var GameLogTable = &stdbGameLogTableHandle{}

func (t *stdbGameLogTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("game_log")
	if err != nil {
		panic(fmt.Sprintf("GameLogTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbGameLogTableHandle) Insert(row GameLog) GameLog {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteGameLog(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("GameLogTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbGameLogTableHandle) Delete(row GameLog) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteGameLog(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("GameLogTable.Delete: %v", err))
	}
}

func (t *stdbGameLogTableHandle) Scan() (runtime.TableIterator[GameLog], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[GameLog](iter, func(r bsatn.Reader, v *GameLog) error {
		return stdbReadGameLog(r, v)
	}), nil
}

func (t *stdbGameLogTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbGameLogTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	case 0: // create_player
		stdbReader := bsatn.NewZeroCopyReader(args)
		var name string
		{
			v, err := stdbReader.GetString()
			if err != nil {
				return fmt.Errorf("decode arg 0: %w", err)
			}
			name = v
		}
		CreatePlayer(ctx, name)
		return nil
	case 1: // update_score
		stdbReader := bsatn.NewZeroCopyReader(args)
		var playerId uint64
		{
			v, err := stdbReader.GetU64()
			if err != nil {
				return fmt.Errorf("decode arg 0: %w", err)
			}
			playerId = v
		}
		var delta int64
		{
			v, err := stdbReader.GetI64()
			if err != nil {
				return fmt.Errorf("decode arg 1: %w", err)
			}
			delta = v
		}
		UpdateScore(ctx, playerId, delta)
		return nil
	case 2: // remove_player
		stdbReader := bsatn.NewZeroCopyReader(args)
		var playerId uint64
		{
			v, err := stdbReader.GetU64()
			if err != nil {
				return fmt.Errorf("decode arg 0: %w", err)
			}
			playerId = v
		}
		return RemovePlayer(ctx, playerId)
	case 3: // Init (__init__)
		Init(ctx)
		return nil
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refStatus := ts.Reserve()
	refPlayer := ts.Reserve()
	refPosition := ts.Reserve()
	refGameLog := ts.Reserve()

	ts.Set(refStatus, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Online", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Offline", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Away", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
	)))

	ts.Set(refPlayer, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
		types.ProductTypeElement{Name: "owner", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__identity__", AlgebraicType: types.AlgTypeU256()}))},
		types.ProductTypeElement{Name: "position", AlgebraicType: types.AlgTypeRef(refPosition)},
		types.ProductTypeElement{Name: "status", AlgebraicType: types.AlgTypeRef(refStatus)},
		types.ProductTypeElement{Name: "score", AlgebraicType: types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "some", AlgebraicType: types.AlgTypeU64()},
			types.SumTypeVariant{Name: "none", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		))},
	)))

	ts.Set(refPosition, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "x", AlgebraicType: types.AlgTypeF64()},
		types.ProductTypeElement{Name: "y", AlgebraicType: types.AlgTypeF64()},
	)))

	ts.Set(refGameLog, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "message", AlgebraicType: types.AlgTypeString()},
		types.ProductTypeElement{Name: "level", AlgebraicType: types.AlgTypeU8()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Status", refStatus).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Player", refPlayer).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Position", refPosition).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "GameLog", refGameLog).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("player").
		WithProductTypeRef(refPlayer).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("player_id_idx_btree"), 0).Build()).
		WithSequence(moduledef.NewSequenceDefBuilder(nil, 0).Build()).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 1)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("player_name_idx_btree"), 1).Build()).
		Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("game_log").
		WithProductTypeRef(refGameLog).
		WithTableAccess(moduledef.TableAccessPublic).
		WithIsEvent(true).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("create_player").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
		)).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("update_score").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "playerId", AlgebraicType: types.AlgTypeU64()},
			types.ProductTypeElement{Name: "delta", AlgebraicType: types.AlgTypeI64()},
		)).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("remove_player").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "playerId", AlgebraicType: types.AlgTypeU64()},
		)).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("__init__").
		WithParams(types.NewProductType()).
		WithVisibility(moduledef.FunctionVisibilityPrivate).
		WithErrReturnType(types.AlgTypeString()).
		Build())
	builder = builder.AddLifecycleReducer(moduledef.NewLifecycleReducerDef(moduledef.LifecycleInit, "__init__"))

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
