// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWriteStatus(w bsatn.Writer, v *Status) {
	w.PutU8(uint8(*v))
}

func StdbReadStatus(r bsatn.Reader, v *Status) error {
	tag, err := r.GetU8()
	if err != nil {
		return fmt.Errorf("decode Status: %w", err)
	}
	if int(tag) >= 3 {
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "Status"}
	}
	*v = Status(tag)
	return nil
}

func StdbWriteWidget(w bsatn.Writer, v *Widget) {
	w.PutU64(v.Id)
	w.PutU32(v.Count)
	w.PutI64(v.Score)
	w.PutF64(v.Ratio)
	w.PutBool(v.Active)
	w.PutString(v.Name)
	w.PutString(v.Note)
	StdbWriteStatus(w, &v.State)
	if v.Maybe != nil {
		w.PutSumTag(0) // Some
		w.PutU64((*v.Maybe))
	} else {
		w.PutSumTag(1) // None
	}
	if v.Some != nil {
		w.PutSumTag(0) // Some
		w.PutU32((*v.Some))
	} else {
		w.PutSumTag(1) // None
	}
	bsatn.WriteByteArray(w, v.Blob)
	StdbWritePoint(w, &v.Origin)
}

func StdbReadWidget(r bsatn.Reader, v *Widget) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Count, err = r.GetU32(); err != nil {
		return fmt.Errorf("decode Count: %w", err)
	}
	if v.Score, err = r.GetI64(); err != nil {
		return fmt.Errorf("decode Score: %w", err)
	}
	if v.Ratio, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode Ratio: %w", err)
	}
	if v.Active, err = r.GetBool(); err != nil {
		return fmt.Errorf("decode Active: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	if v.Note, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Note: %w", err)
	}
	if err = StdbReadStatus(r, &v.State); err != nil {
		return fmt.Errorf("decode State: %w", err)
	}
	{
		var tag uint8
		if tag, err = r.GetU8(); err != nil {
			return fmt.Errorf("decode Maybe tag: %w", err)
		}
		if tag == 0 {
			var tmpMaybe uint64
			if tmpMaybe, err = r.GetU64(); err != nil {
				return fmt.Errorf("decode Maybe_val: %w", err)
			}
			v.Maybe = &tmpMaybe
		} else {
			v.Maybe = nil
		}
	}
	{
		var tag uint8
		if tag, err = r.GetU8(); err != nil {
			return fmt.Errorf("decode Some tag: %w", err)
		}
		if tag == 0 {
			var tmpSome uint32
			if tmpSome, err = r.GetU32(); err != nil {
				return fmt.Errorf("decode Some_val: %w", err)
			}
			v.Some = &tmpSome
		} else {
			v.Some = nil
		}
	}
	if v.Blob, err = bsatn.ReadByteArray(r); err != nil {
		return fmt.Errorf("decode Blob: %w", err)
	}
	if err = StdbReadPoint(r, &v.Origin); err != nil {
		return fmt.Errorf("decode Origin: %w", err)
	}
	return nil
}

func StdbWritePoint(w bsatn.Writer, v *Point) {
	w.PutF64(v.X)
	w.PutF64(v.Y)
}

func StdbReadPoint(r bsatn.Reader, v *Point) error {
	var err error
	if v.X, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode X: %w", err)
	}
	if v.Y, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode Y: %w", err)
	}
	return nil
}

type stdbWidgetTableHandle struct {
	tableId  uint32
	resolved bool
}

var WidgetTable = &stdbWidgetTableHandle{}

func (t *stdbWidgetTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("widget")
	if err != nil {
		panic(fmt.Sprintf("WidgetTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbWidgetTableHandle) Insert(row Widget) Widget {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWriteWidget(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.Insert: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbWidgetTableHandle) Delete(row Widget) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWriteWidget(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("WidgetTable.Delete: %v", err))
	}
}

func (t *stdbWidgetTableHandle) Scan() (runtime.TableIterator[Widget], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Widget](iter, func(r bsatn.Reader, v *Widget) error {
		return StdbReadWidget(r, v)
	}), nil
}

func (t *stdbWidgetTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbWidgetTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbWidgetTableHandle) FindById(key uint64) (Widget, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("widget_id_idx_btree")
	if err != nil {
		var zero Widget
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Widget
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Widget
		return zero, false, err
	}
	var result Widget
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadWidget(r, &result); err != nil {
		var zero Widget
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbWidgetTableHandle) UpdateById(row Widget) Widget {
	t.resolve()
	indexId, err := runtime.GetIndexId("widget_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWriteWidget(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.UpdateById: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbWidgetTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("widget_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.DeleteById: %v", err))
	}
	return deleted
}

func (t *stdbWidgetTableHandle) FilterByName(key string) (runtime.TableIterator[Widget], error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("widget_name_idx_btree")
	if err != nil {
		return nil, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutString(key)
	keyBytes := make([]byte, len(runtime.GlobalWriter.Bytes()))
	copy(keyBytes, runtime.GlobalWriter.Bytes())
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, keyBytes)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Widget](iter, func(r bsatn.Reader, v *Widget) error {
		return StdbReadWidget(r, v)
	}), nil
}

func (t *stdbWidgetTableHandle) DeleteByName(key string) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("widget_name_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.DeleteByName: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutString(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("WidgetTable.DeleteByName: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refStatus := ts.Reserve()
	refWidget := ts.Reserve()
	refPoint := ts.Reserve()

	ts.Set(refStatus, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Online", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Offline", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Away", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
	)))

	ts.Set(refWidget, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "count", AlgebraicType: types.AlgTypeU32()},
		types.ProductTypeElement{Name: "score", AlgebraicType: types.AlgTypeI64()},
		types.ProductTypeElement{Name: "ratio", AlgebraicType: types.AlgTypeF64()},
		types.ProductTypeElement{Name: "active", AlgebraicType: types.AlgTypeBool()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
		types.ProductTypeElement{Name: "note", AlgebraicType: types.AlgTypeString()},
		types.ProductTypeElement{Name: "state", AlgebraicType: types.AlgTypeRef(refStatus)},
		types.ProductTypeElement{Name: "maybe", AlgebraicType: types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "some", AlgebraicType: types.AlgTypeU64()},
			types.SumTypeVariant{Name: "none", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		))},
		types.ProductTypeElement{Name: "some", AlgebraicType: types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "some", AlgebraicType: types.AlgTypeU32()},
			types.SumTypeVariant{Name: "none", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		))},
		types.ProductTypeElement{Name: "blob", AlgebraicType: types.AlgTypeArray(types.AlgTypeU8())},
		types.ProductTypeElement{Name: "origin", AlgebraicType: types.AlgTypeRef(refPoint)},
	)))

	ts.Set(refPoint, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "x", AlgebraicType: types.AlgTypeF64()},
		types.ProductTypeElement{Name: "y", AlgebraicType: types.AlgTypeF64()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Status", refStatus).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Widget", refWidget).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Point", refPoint).
		WithCustomOrdering(true).Build())

	stdbDef_widget_count := bsatn.NewWriter(16)
	stdbDef_widget_count.PutU32(5)
	stdbDef_widget_score := bsatn.NewWriter(16)
	stdbDef_widget_score.PutI64(-3)
	stdbDef_widget_ratio := bsatn.NewWriter(16)
	stdbDef_widget_ratio.PutF64(1.5)
	stdbDef_widget_active := bsatn.NewWriter(16)
	stdbDef_widget_active.PutBool(true)
	stdbDef_widget_name := bsatn.NewWriter(16)
	stdbDef_widget_name.PutString("Unknown")
	stdbDef_widget_note := bsatn.NewWriter(16)
	stdbDef_widget_note.PutString("")
	stdbDef_widget_state := bsatn.NewWriter(16)
	stdbDef_widget_state.PutSumTag(1)
	stdbDef_widget_maybe := bsatn.NewWriter(16)
	stdbDef_widget_maybe.PutSumTag(1)
	stdbDef_widget_some := bsatn.NewWriter(16)
	stdbDef_widget_some.PutSumTag(0)
	stdbDef_widget_some.PutU32(7)
	stdbDef_widget_blob := bsatn.NewWriter(16)
	stdbDef_widget_blob.PutArrayLen(4)
	stdbDef_widget_blob.PutBytes([]byte{0x01, 0x02, 0x03, 0x04})
	stdbDef_widget_origin := bsatn.NewWriter(16)
	stdbDef_widget_origin.PutBytes([]byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00})
	builder = builder.AddTable(moduledef.NewTableDefBuilder("widget").
		WithProductTypeRef(refWidget).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("widget_id_idx_btree"), 0).Build()).
		WithSequence(moduledef.NewSequenceDefBuilder(nil, 0).Build()).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("widget_name_idx_btree"), 5).Build()).
		WithDefaultValue(moduledef.NewColumnDefaultValue(1, stdbDef_widget_count.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(2, stdbDef_widget_score.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(3, stdbDef_widget_ratio.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(4, stdbDef_widget_active.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(5, stdbDef_widget_name.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(6, stdbDef_widget_note.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(7, stdbDef_widget_state.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(8, stdbDef_widget_maybe.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(9, stdbDef_widget_some.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(10, stdbDef_widget_blob.Bytes())).
		WithDefaultValue(moduledef.NewColumnDefaultValue(11, stdbDef_widget_origin.Bytes())).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
