// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// selfViewViewDef implements cache.TypedTableDef for the selfView view.
type selfViewViewDef struct{}

func (selfViewViewDef) TableName() string { return "self" }

func (selfViewViewDef) DecodeRow(r bsatn.Reader) (*Self, error) {
	return ReadSelf(r)
}

func (selfViewViewDef) EncodeRow(row *Self) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// SelfViewView is a type-safe view cache for Self rows.
type SelfViewView = cache.TypedTableCache[*Self]
