// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *Self) WriteBsatn(w bsatn.Writer) {
	w.PutU32(v.ID)
	w.PutString(v.Name)
}

func ReadSelf(r bsatn.Reader) (*Self, error) {
	v := &Self{}
	var err error
	v.ID, err = r.GetU32()
	if err != nil {
		return nil, err
	}
	v.Name, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}
