// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type addUserArgs struct {
	Name  string
	Email string
}

func (a *addUserArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Name)
	w.PutString(a.Email)
}

// CallAddUser calls the add_user reducer on the server.
func CallAddUser(conn client.DbConnection, name string, email string) error {
	args := &addUserArgs{
		Name:  name,
		Email: email,
	}
	return conn.CallReducer("add_user", args)
}
