// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *User) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutString(v.Name)
	w.PutString(v.Email)
}

func ReadUser(r bsatn.Reader) (*User, error) {
	v := &User{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Name, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Email, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}
