// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// usersTableDef implements cache.TypedTableDef for the users table.
type usersTableDef struct{}

func (usersTableDef) TableName() string { return "users" }

func (usersTableDef) DecodeRow(r bsatn.Reader) (*User, error) {
	return ReadUser(r)
}

func (usersTableDef) EncodeRow(row *User) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (usersTableDef) PrimaryKey(row *User) uint64 {
	return row.ID
}

// UserTable is a type-safe table cache for users rows.
type UserTable = cache.TypedTableCache[*User]
