// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteEntity(w bsatn.Writer, v *Entity) {
	w.PutU64(v.Id)
	w.PutString(v.Name)
}

func stdbReadEntity(r bsatn.Reader, v *Entity) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	return nil
}

type stdbActiveEntityTableHandle struct {
	tableId  uint32
	resolved bool
}

var ActiveEntityTable = &stdbActiveEntityTableHandle{}

func (t *stdbActiveEntityTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("active_entity")
	if err != nil {
		panic(fmt.Sprintf("ActiveEntityTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbActiveEntityTableHandle) Insert(row Entity) Entity {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteEntity(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ActiveEntityTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbActiveEntityTableHandle) Delete(row Entity) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteEntity(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("ActiveEntityTable.Delete: %v", err))
	}
}

func (t *stdbActiveEntityTableHandle) Scan() (runtime.TableIterator[Entity], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Entity](iter, func(r bsatn.Reader, v *Entity) error {
		return stdbReadEntity(r, v)
	}), nil
}

func (t *stdbActiveEntityTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbActiveEntityTableHandle) FindById(key uint64) (Entity, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("active_entity_id_idx_btree")
	if err != nil {
		var zero Entity
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Entity
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Entity
		return zero, false, err
	}
	var result Entity
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadEntity(r, &result); err != nil {
		var zero Entity
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbActiveEntityTableHandle) UpdateById(row Entity) Entity {
	t.resolve()
	indexId, err := runtime.GetIndexId("active_entity_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("ActiveEntityTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWriteEntity(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ActiveEntityTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbActiveEntityTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("active_entity_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("ActiveEntityTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ActiveEntityTable.DeleteById: %v", err))
	}
	return deleted
}

type stdbInactiveEntityTableHandle struct {
	tableId  uint32
	resolved bool
}

var InactiveEntityTable = &stdbInactiveEntityTableHandle{}

func (t *stdbInactiveEntityTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("inactive_entity")
	if err != nil {
		panic(fmt.Sprintf("InactiveEntityTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbInactiveEntityTableHandle) Insert(row Entity) Entity {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteEntity(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("InactiveEntityTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbInactiveEntityTableHandle) Delete(row Entity) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteEntity(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("InactiveEntityTable.Delete: %v", err))
	}
}

func (t *stdbInactiveEntityTableHandle) Scan() (runtime.TableIterator[Entity], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Entity](iter, func(r bsatn.Reader, v *Entity) error {
		return stdbReadEntity(r, v)
	}), nil
}

func (t *stdbInactiveEntityTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbInactiveEntityTableHandle) FindById(key uint64) (Entity, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("inactive_entity_id_idx_btree")
	if err != nil {
		var zero Entity
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Entity
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Entity
		return zero, false, err
	}
	var result Entity
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadEntity(r, &result); err != nil {
		var zero Entity
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbInactiveEntityTableHandle) UpdateById(row Entity) Entity {
	t.resolve()
	indexId, err := runtime.GetIndexId("inactive_entity_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("InactiveEntityTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWriteEntity(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("InactiveEntityTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbInactiveEntityTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("inactive_entity_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("InactiveEntityTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("InactiveEntityTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refEntity := ts.Reserve()

	ts.Set(refEntity, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Entity", refEntity).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("active_entity").
		WithProductTypeRef(refEntity).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("active_entity_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("inactive_entity").
		WithProductTypeRef(refEntity).
		WithTableAccess(moduledef.TableAccessPrivate).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("inactive_entity_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
