// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

type User struct {
	ID    uint64
	Name  string
	Email string
}

type UserSummary struct {
	UserID      uint64
	DisplayName string
}
