// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// userSummaryViewDef implements cache.TypedTableDef for the UserSummary view.
type userSummaryViewDef struct{}

func (userSummaryViewDef) TableName() string { return "UserSummary" }

func (userSummaryViewDef) DecodeRow(r bsatn.Reader) (*UserSummary, error) {
	return ReadUserSummary(r)
}

func (userSummaryViewDef) EncodeRow(row *UserSummary) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// UserSummaryView is a type-safe view cache for UserSummary rows.
type UserSummaryView = cache.TypedTableCache[*UserSummary]
