// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWriteSpecial(w bsatn.Writer, v *Special) {
	w.PutU64(v.Id)
	{
		b := v.Owner.Bytes()
		w.PutBytes(b[:])
	}
	{
		b := v.ConnId.Bytes()
		w.PutBytes(b[:])
	}
	w.PutI64(v.CreatedAt.Microseconds())
	w.PutI64(v.Duration.Microseconds())
	{
		b := v.ExternalId.Bytes()
		w.PutBytes(b[:])
	}
	{
		b := v.BigNum.Bytes()
		w.PutBytes(b[:])
	}
	{
		b := v.BigSigned.Bytes()
		w.PutBytes(b[:])
	}
}

func StdbReadSpecial(r bsatn.Reader, v *Special) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	{
		var tmp types.Identity
		if tmp, err = types.ReadIdentity(r); err != nil {
			return fmt.Errorf("decode Owner: %w", err)
		}
		v.Owner = tmp
	}
	{
		var tmp types.ConnectionId
		if tmp, err = types.ReadConnectionId(r); err != nil {
			return fmt.Errorf("decode ConnId: %w", err)
		}
		v.ConnId = tmp
	}
	{
		var tmp types.Timestamp
		if tmp, err = types.ReadTimestamp(r); err != nil {
			return fmt.Errorf("decode CreatedAt: %w", err)
		}
		v.CreatedAt = tmp
	}
	{
		var tmp types.TimeDuration
		if tmp, err = types.ReadTimeDuration(r); err != nil {
			return fmt.Errorf("decode Duration: %w", err)
		}
		v.Duration = tmp
	}
	{
		var tmp types.Uuid
		if tmp, err = types.ReadUuid(r); err != nil {
			return fmt.Errorf("decode ExternalId: %w", err)
		}
		v.ExternalId = tmp
	}
	{
		var tmp types.Uint128
		if tmp, err = types.ReadUint128(r); err != nil {
			return fmt.Errorf("decode BigNum: %w", err)
		}
		v.BigNum = tmp
	}
	{
		var tmp types.Int128
		if tmp, err = types.ReadInt128(r); err != nil {
			return fmt.Errorf("decode BigSigned: %w", err)
		}
		v.BigSigned = tmp
	}
	return nil
}

type stdbSpecialTableHandle struct {
	tableId  uint32
	resolved bool
}

var SpecialTable = &stdbSpecialTableHandle{}

func (t *stdbSpecialTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("special")
	if err != nil {
		panic(fmt.Sprintf("SpecialTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbSpecialTableHandle) Insert(row Special) Special {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWriteSpecial(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("SpecialTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbSpecialTableHandle) Delete(row Special) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWriteSpecial(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("SpecialTable.Delete: %v", err))
	}
}

func (t *stdbSpecialTableHandle) Scan() (runtime.TableIterator[Special], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Special](iter, func(r bsatn.Reader, v *Special) error {
		return StdbReadSpecial(r, v)
	}), nil
}

func (t *stdbSpecialTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbSpecialTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbSpecialTableHandle) FindById(key uint64) (Special, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("special_id_idx_btree")
	if err != nil {
		var zero Special
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Special
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Special
		return zero, false, err
	}
	var result Special
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadSpecial(r, &result); err != nil {
		var zero Special
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbSpecialTableHandle) UpdateById(row Special) Special {
	t.resolve()
	indexId, err := runtime.GetIndexId("special_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("SpecialTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWriteSpecial(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("SpecialTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbSpecialTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("special_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("SpecialTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("SpecialTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refSpecial := ts.Reserve()

	ts.Set(refSpecial, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "owner", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__identity__", AlgebraicType: types.AlgTypeU256()}))},
		types.ProductTypeElement{Name: "conn_id", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__connection_id__", AlgebraicType: types.AlgTypeU128()}))},
		types.ProductTypeElement{Name: "created_at", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__timestamp_micros_since_unix_epoch__", AlgebraicType: types.AlgTypeI64()}))},
		types.ProductTypeElement{Name: "duration", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__time_duration_micros__", AlgebraicType: types.AlgTypeI64()}))},
		types.ProductTypeElement{Name: "external_id", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__uuid__", AlgebraicType: types.AlgTypeU128()}))},
		types.ProductTypeElement{Name: "big_num", AlgebraicType: types.AlgTypeU128()},
		types.ProductTypeElement{Name: "big_signed", AlgebraicType: types.AlgTypeI128()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Special", refSpecial).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("special").
		WithProductTypeRef(refSpecial).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("special_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
