// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWriteScheduleAt(w bsatn.Writer, sa types.ScheduleAt) {
	switch v := sa.(type) {
	case types.ScheduleAtInterval:
		w.PutSumTag(0)
		w.PutI64(v.Value.Microseconds())
	case types.ScheduleAtTime:
		w.PutSumTag(1)
		w.PutI64(v.Value.Microseconds())
	default:
		panic(fmt.Sprintf("StdbWriteScheduleAt: unknown variant %T", sa))
	}
}

func StdbWriteScheduledProcTable(w bsatn.Writer, v *ScheduledProcTable) {
	w.PutU64(v.ScheduledId)
	StdbWriteScheduleAt(w, v.ScheduledAt)
}

func StdbReadScheduledProcTable(r bsatn.Reader, v *ScheduledProcTable) error {
	var err error
	if v.ScheduledId, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode ScheduledId: %w", err)
	}
	{
		var tmp types.ScheduleAt
		if tmp, err = types.ReadScheduleAt(r); err != nil {
			return fmt.Errorf("decode ScheduledAt: %w", err)
		}
		v.ScheduledAt = tmp
	}
	return nil
}

type stdbScheduledProcTableTableHandle struct {
	tableId  uint32
	resolved bool
}

var ScheduledProcTableTable = &stdbScheduledProcTableTableHandle{}

func (t *stdbScheduledProcTableTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("scheduled_proc_table")
	if err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbScheduledProcTableTableHandle) Insert(row ScheduledProcTable) ScheduledProcTable {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWriteScheduledProcTable(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable.Insert: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.ScheduledId = v
		}
	}
	return row
}

func (t *stdbScheduledProcTableTableHandle) Delete(row ScheduledProcTable) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWriteScheduledProcTable(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable.Delete: %v", err))
	}
}

func (t *stdbScheduledProcTableTableHandle) Scan() (runtime.TableIterator[ScheduledProcTable], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[ScheduledProcTable](iter, func(r bsatn.Reader, v *ScheduledProcTable) error {
		return StdbReadScheduledProcTable(r, v)
	}), nil
}

func (t *stdbScheduledProcTableTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbScheduledProcTableTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbScheduledProcTableTableHandle) FindByScheduledId(key uint64) (ScheduledProcTable, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("scheduled_proc_table_scheduled_id_idx_btree")
	if err != nil {
		var zero ScheduledProcTable
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero ScheduledProcTable
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero ScheduledProcTable
		return zero, false, err
	}
	var result ScheduledProcTable
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadScheduledProcTable(r, &result); err != nil {
		var zero ScheduledProcTable
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbScheduledProcTableTableHandle) UpdateByScheduledId(row ScheduledProcTable) ScheduledProcTable {
	t.resolve()
	indexId, err := runtime.GetIndexId("scheduled_proc_table_scheduled_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable.UpdateByScheduledId: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWriteScheduledProcTable(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable.UpdateByScheduledId: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.ScheduledId = v
		}
	}
	return row
}

func (t *stdbScheduledProcTableTableHandle) DeleteByScheduledId(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("scheduled_proc_table_scheduled_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable.DeleteByScheduledId: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("ScheduledProcTableTable.DeleteByScheduledId: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	case 0: // scheduled_proc
		ScheduledProc(ctx)
		return nil
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refScheduledProcTable := ts.Reserve()

	ts.Set(refScheduledProcTable, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "scheduled_id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "scheduled_at", AlgebraicType: types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "Interval", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__time_duration_micros__", AlgebraicType: types.AlgTypeI64()}))},
			types.SumTypeVariant{Name: "Time", AlgebraicType: types.AlgTypeProduct(types.NewProductType(types.ProductTypeElement{Name: "__timestamp_micros_since_unix_epoch__", AlgebraicType: types.AlgTypeI64()}))},
		))},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "ScheduledProcTable", refScheduledProcTable).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("scheduled_proc_table").
		WithProductTypeRef(refScheduledProcTable).
		WithTableAccess(moduledef.TableAccessPrivate).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("scheduled_proc_table_scheduled_id_idx_btree"), 0).Build()).
		WithSequence(moduledef.NewSequenceDefBuilder(nil, 0).Build()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("scheduled_proc").
		WithParams(types.NewProductType()).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.AddSchedule(moduledef.NewScheduleDef(nil, "scheduled_proc_table", 1, "scheduled_proc"))

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
