// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// mapEntityTableDef implements cache.TypedTableDef for the MapEntity table.
type mapEntityTableDef struct{}

func (mapEntityTableDef) TableName() string { return "MapEntity" }

func (mapEntityTableDef) DecodeRow(r bsatn.Reader) (*MapEntity, error) {
	return ReadMapEntity(r)
}

func (mapEntityTableDef) EncodeRow(row *MapEntity) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (mapEntityTableDef) PrimaryKey(row *MapEntity) uint64 {
	return row.ID
}

// MapEntityTable is a type-safe table cache for MapEntity rows.
type MapEntityTable = cache.TypedTableCache[*MapEntity]
