// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *MapEntity) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutMapLen(uint32(len(v.Metadata)))
	for k, v := range v.Metadata {
		w.PutString(k)
		w.PutString(v)
	}
	w.PutMapLen(uint32(len(v.Scores)))
	for k, v := range v.Scores {
		w.PutU32(k)
		w.PutI64(v)
	}
}

func ReadMapEntity(r bsatn.Reader) (*MapEntity, error) {
	v := &MapEntity{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	{
		var mapLen uint32
		mapLen, err = r.GetMapLen()
		if err != nil {
			return nil, err
		}
		v.Metadata = make(map[string]string, mapLen)
		for i := uint32(0); i < mapLen; i++ {
			var k string
			var val string
			k, err = r.GetString()
			if err != nil {
				return nil, err
			}
			val, err = r.GetString()
			if err != nil {
				return nil, err
			}
			v.Metadata[k] = val
		}
	}
	{
		var mapLen uint32
		mapLen, err = r.GetMapLen()
		if err != nil {
			return nil, err
		}
		v.Scores = make(map[uint32]int64, mapLen)
		for i := uint32(0); i < mapLen; i++ {
			var k uint32
			var val int64
			k, err = r.GetU32()
			if err != nil {
				return nil, err
			}
			val, err = r.GetI64()
			if err != nil {
				return nil, err
			}
			v.Scores[k] = val
		}
	}
	return v, nil
}
