// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// eventLogTableDef implements cache.TypedTableDef for the EventLog table.
type eventLogTableDef struct{}

func (eventLogTableDef) TableName() string { return "EventLog" }

func (eventLogTableDef) DecodeRow(r bsatn.Reader) (*EventLog, error) {
	return ReadEventLog(r)
}

func (eventLogTableDef) EncodeRow(row *EventLog) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// EventLogTable is a type-safe table cache for EventLog rows.
type EventLogTable = cache.TypedTableCache[*EventLog]
