// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *EventLog) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.EventType)
	w.PutString(v.Payload)
	w.PutU64(v.Timestamp)
}

func ReadEventLog(r bsatn.Reader) (*EventLog, error) {
	v := &EventLog{}
	var err error
	v.EventType, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Payload, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Timestamp, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	return v, nil
}
