// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteSecret(w bsatn.Writer, v *Secret) {
	w.PutU64(v.Id)
	w.PutString(v.Value)
}

func stdbReadSecret(r bsatn.Reader, v *Secret) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Value, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Value: %w", err)
	}
	return nil
}

type stdbSecretTableHandle struct {
	tableId  uint32
	resolved bool
}

var SecretTable = &stdbSecretTableHandle{}

func (t *stdbSecretTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("secret")
	if err != nil {
		panic(fmt.Sprintf("SecretTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbSecretTableHandle) Insert(row Secret) Secret {
	t.resolve()
	runtime.GlobalWriter.Reset()
	stdbWriteSecret(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("SecretTable.Insert: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbSecretTableHandle) Delete(row Secret) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	stdbWriteSecret(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("SecretTable.Delete: %v", err))
	}
}

func (t *stdbSecretTableHandle) Scan() (runtime.TableIterator[Secret], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Secret](iter, func(r bsatn.Reader, v *Secret) error {
		return stdbReadSecret(r, v)
	}), nil
}

func (t *stdbSecretTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbSecretTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbSecretTableHandle) FindById(key uint64) (Secret, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("secret_id_idx_btree")
	if err != nil {
		var zero Secret
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Secret
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Secret
		return zero, false, err
	}
	var result Secret
	r := bsatn.NewZeroCopyReader(data)
	if err := stdbReadSecret(r, &result); err != nil {
		var zero Secret
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbSecretTableHandle) UpdateById(row Secret) Secret {
	t.resolve()
	indexId, err := runtime.GetIndexId("secret_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("SecretTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	stdbWriteSecret(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("SecretTable.UpdateById: %v", err))
	}
	_ = seqBytes
	return row
}

func (t *stdbSecretTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("secret_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("SecretTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("SecretTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refSecret := ts.Reserve()

	ts.Set(refSecret, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "value", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Secret", refSecret).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("secret").
		WithProductTypeRef(refSecret).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("secret_id_idx_btree"), 0).Build()).
		Build())

	builder = builder.AddRowLevelSecurity("SELECT * FROM secret WHERE owner = @sender")

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
