// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWriteAllPrimitives(w bsatn.Writer, v *AllPrimitives) {
	w.PutU64(v.Id)
	w.PutBool(v.ABool)
	w.PutU8(v.AU8)
	w.PutU16(v.AU16)
	w.PutU32(v.AU32)
	w.PutU64(v.AU64)
	w.PutI8(v.AI8)
	w.PutI16(v.AI16)
	w.PutI32(v.AI32)
	w.PutI64(v.AI64)
	w.PutF32(v.AF32)
	w.PutF64(v.AF64)
	w.PutString(v.AString)
}

func StdbReadAllPrimitives(r bsatn.Reader, v *AllPrimitives) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.ABool, err = r.GetBool(); err != nil {
		return fmt.Errorf("decode ABool: %w", err)
	}
	if v.AU8, err = r.GetU8(); err != nil {
		return fmt.Errorf("decode AU8: %w", err)
	}
	if v.AU16, err = r.GetU16(); err != nil {
		return fmt.Errorf("decode AU16: %w", err)
	}
	if v.AU32, err = r.GetU32(); err != nil {
		return fmt.Errorf("decode AU32: %w", err)
	}
	if v.AU64, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode AU64: %w", err)
	}
	if v.AI8, err = r.GetI8(); err != nil {
		return fmt.Errorf("decode AI8: %w", err)
	}
	if v.AI16, err = r.GetI16(); err != nil {
		return fmt.Errorf("decode AI16: %w", err)
	}
	if v.AI32, err = r.GetI32(); err != nil {
		return fmt.Errorf("decode AI32: %w", err)
	}
	if v.AI64, err = r.GetI64(); err != nil {
		return fmt.Errorf("decode AI64: %w", err)
	}
	if v.AF32, err = r.GetF32(); err != nil {
		return fmt.Errorf("decode AF32: %w", err)
	}
	if v.AF64, err = r.GetF64(); err != nil {
		return fmt.Errorf("decode AF64: %w", err)
	}
	if v.AString, err = r.GetString(); err != nil {
		return fmt.Errorf("decode AString: %w", err)
	}
	return nil
}

type stdbAllPrimitivesTableHandle struct {
	tableId  uint32
	resolved bool
}

var AllPrimitivesTable = &stdbAllPrimitivesTableHandle{}

func (t *stdbAllPrimitivesTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("all_primitives")
	if err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbAllPrimitivesTableHandle) Insert(row AllPrimitives) AllPrimitives {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWriteAllPrimitives(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable.Insert: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbAllPrimitivesTableHandle) Delete(row AllPrimitives) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWriteAllPrimitives(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable.Delete: %v", err))
	}
}

func (t *stdbAllPrimitivesTableHandle) Scan() (runtime.TableIterator[AllPrimitives], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[AllPrimitives](iter, func(r bsatn.Reader, v *AllPrimitives) error {
		return StdbReadAllPrimitives(r, v)
	}), nil
}

func (t *stdbAllPrimitivesTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbAllPrimitivesTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbAllPrimitivesTableHandle) FindById(key uint64) (AllPrimitives, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("all_primitives_id_idx_btree")
	if err != nil {
		var zero AllPrimitives
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero AllPrimitives
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero AllPrimitives
		return zero, false, err
	}
	var result AllPrimitives
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadAllPrimitives(r, &result); err != nil {
		var zero AllPrimitives
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbAllPrimitivesTableHandle) UpdateById(row AllPrimitives) AllPrimitives {
	t.resolve()
	indexId, err := runtime.GetIndexId("all_primitives_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWriteAllPrimitives(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable.UpdateById: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbAllPrimitivesTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("all_primitives_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("AllPrimitivesTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refAllPrimitives := ts.Reserve()

	ts.Set(refAllPrimitives, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "a_bool", AlgebraicType: types.AlgTypeBool()},
		types.ProductTypeElement{Name: "au8", AlgebraicType: types.AlgTypeU8()},
		types.ProductTypeElement{Name: "au16", AlgebraicType: types.AlgTypeU16()},
		types.ProductTypeElement{Name: "au32", AlgebraicType: types.AlgTypeU32()},
		types.ProductTypeElement{Name: "au64", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "ai8", AlgebraicType: types.AlgTypeI8()},
		types.ProductTypeElement{Name: "ai16", AlgebraicType: types.AlgTypeI16()},
		types.ProductTypeElement{Name: "ai32", AlgebraicType: types.AlgTypeI32()},
		types.ProductTypeElement{Name: "ai64", AlgebraicType: types.AlgTypeI64()},
		types.ProductTypeElement{Name: "af32", AlgebraicType: types.AlgTypeF32()},
		types.ProductTypeElement{Name: "af64", AlgebraicType: types.AlgTypeF64()},
		types.ProductTypeElement{Name: "a_string", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "AllPrimitives", refAllPrimitives).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("all_primitives").
		WithProductTypeRef(refAllPrimitives).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("all_primitives_id_idx_btree"), 0).Build()).
		WithSequence(moduledef.NewSequenceDefBuilder(nil, 0).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
