// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWritePerson(w bsatn.Writer, v *Person) {
	w.PutU64(v.Id)
	w.PutString(v.Name)
}

func StdbReadPerson(r bsatn.Reader, v *Person) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	return nil
}

type stdbPersonTableHandle struct {
	tableId  uint32
	resolved bool
}

var PersonTable = &stdbPersonTableHandle{}

func (t *stdbPersonTableHandle) resolve() {
	if t.resolved {
		return
	}
	id, err := runtime.GetTableId("person")
	if err != nil {
		panic(fmt.Sprintf("PersonTable: resolve table: %v", err))
	}
	t.tableId = id
	t.resolved = true
}

func (t *stdbPersonTableHandle) Insert(row Person) Person {
	t.resolve()
	runtime.GlobalWriter.Reset()
	StdbWritePerson(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreInsertBSATN(t.tableId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PersonTable.Insert: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbPersonTableHandle) Delete(row Person) {
	t.resolve()
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutArrayLen(1)
	StdbWritePerson(runtime.GlobalWriter, &row)
	if _, err := sys.DatastoreDeleteAllByEqBSATN(t.tableId, runtime.GlobalWriter.Bytes()); err != nil {
		panic(fmt.Sprintf("PersonTable.Delete: %v", err))
	}
}

func (t *stdbPersonTableHandle) Scan() (runtime.TableIterator[Person], error) {
	t.resolve()
	iter, err := sys.DatastoreTableScanBSATN(t.tableId)
	if err != nil {
		return nil, err
	}
	return runtime.NewTableIterator[Person](iter, func(r bsatn.Reader, v *Person) error {
		return StdbReadPerson(r, v)
	}), nil
}

func (t *stdbPersonTableHandle) Count() (uint64, error) {
	t.resolve()
	return sys.DatastoreTableRowCount(t.tableId)
}

func (t *stdbPersonTableHandle) Clear() (uint64, error) {
	t.resolve()
	return sys.DatastoreClear(t.tableId)
}

func (t *stdbPersonTableHandle) FindById(key uint64) (Person, bool, error) {
	t.resolve()
	indexId, err := runtime.GetIndexId("person_id_idx_btree")
	if err != nil {
		var zero Person
		return zero, false, err
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	iter, err := sys.DatastoreIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		var zero Person
		return zero, false, err
	}
	defer iter.Close()
	data, ok, err := iter.Next()
	if !ok || err != nil {
		var zero Person
		return zero, false, err
	}
	var result Person
	r := bsatn.NewZeroCopyReader(data)
	if err := StdbReadPerson(r, &result); err != nil {
		var zero Person
		return zero, false, err
	}
	return result, true, nil
}

func (t *stdbPersonTableHandle) UpdateById(row Person) Person {
	t.resolve()
	indexId, err := runtime.GetIndexId("person_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("PersonTable.UpdateById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	StdbWritePerson(runtime.GlobalWriter, &row)
	seqBytes, err := sys.DatastoreUpdateBSATN(t.tableId, indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PersonTable.UpdateById: %v", err))
	}
	if len(seqBytes) > 0 {
		seqR := bsatn.NewZeroCopyReader(seqBytes)
		{
			v, _ := seqR.GetU64()
			row.Id = v
		}
	}
	return row
}

func (t *stdbPersonTableHandle) DeleteById(key uint64) uint32 {
	t.resolve()
	indexId, err := runtime.GetIndexId("person_id_idx_btree")
	if err != nil {
		panic(fmt.Sprintf("PersonTable.DeleteById: %v", err))
	}
	runtime.GlobalWriter.Reset()
	runtime.GlobalWriter.PutU64(key)
	deleted, err := sys.DatastoreDeleteByIndexScanPointBSATN(indexId, runtime.GlobalWriter.Bytes())
	if err != nil {
		panic(fmt.Sprintf("PersonTable.DeleteById: %v", err))
	}
	return deleted
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refPerson := ts.Reserve()

	ts.Set(refPerson, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Person", refPerson).
		WithCustomOrdering(true).Build())

	builder = builder.AddTable(moduledef.NewTableDefBuilder("person").
		WithProductTypeRef(refPerson).
		WithTableAccess(moduledef.TableAccessPublic).
		WithPrimaryKey(0).
		WithConstraint(moduledef.NewUniqueConstraint(nil, 0)).
		WithIndex(moduledef.NewBTreeIndexDef(stdbStrPtr("person_id_idx_btree"), 0).Build()).
		WithSequence(moduledef.NewSequenceDefBuilder(nil, 0).Build()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
