// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	case 0: // add_player
		stdbReader := bsatn.NewZeroCopyReader(args)
		var name string
		{
			v, err := stdbReader.GetString()
			if err != nil {
				return fmt.Errorf("decode arg 0: %w", err)
			}
			name = v
		}
		var score uint64
		{
			v, err := stdbReader.GetU64()
			if err != nil {
				return fmt.Errorf("decode arg 1: %w", err)
			}
			score = v
		}
		AddPlayer(ctx, name, score)
		return nil
	case 1: // custom_remove
		stdbReader := bsatn.NewZeroCopyReader(args)
		var id uint64
		{
			v, err := stdbReader.GetU64()
			if err != nil {
				return fmt.Errorf("decode arg 0: %w", err)
			}
			id = v
		}
		return RemovePlayer(ctx, id)
	case 2: // reset_all
		ResetAll(ctx)
		return nil
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("add_player").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
			types.ProductTypeElement{Name: "score", AlgebraicType: types.AlgTypeU64()},
		)).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("custom_remove").
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		)).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.AddReducer(moduledef.NewReducerDefBuilder("reset_all").
		WithParams(types.NewProductType()).
		WithVisibility(moduledef.FunctionVisibilityClientCallable).
		WithErrReturnType(types.AlgTypeString()).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
