// Code generated by stdb-gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/bsatn"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/moduledef"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/reducer"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/runtime"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/sys"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/types"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteActionType(w bsatn.Writer, v *ActionType) {
	w.PutU8(uint8(*v))
}

func stdbReadActionType(r bsatn.Reader, v *ActionType) error {
	tag, err := r.GetU8()
	if err != nil {
		return fmt.Errorf("decode ActionType: %w", err)
	}
	if int(tag) >= 3 {
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "ActionType"}
	}
	*v = ActionType(tag)
	return nil
}

func stdbWriteEffect(w bsatn.Writer, v *Effect) {
	switch val := (*v).(type) {
	case EffectDamage:
		w.PutSumTag(0)
		w.PutU32(val.Amount)
	case EffectBuff:
		w.PutSumTag(1)
		w.PutI64(val.Duration)
		w.PutF32(val.Power)
	default:
		panic(fmt.Sprintf("stdbWriteEffect: unknown variant %T", *v))
	}
}

func stdbReadEffect(r bsatn.Reader, v *Effect) error {
	var err error
	var tag uint8
	if tag, err = r.GetU8(); err != nil {
		return fmt.Errorf("decode Effect tag: %w", err)
	}
	switch tag {
	case 0: // Damage
		var val EffectDamage
		if val.Amount, err = r.GetU32(); err != nil {
			return fmt.Errorf("decode Damage: %w", err)
		}
		*v = val
	case 1: // Buff
		var val EffectBuff
		if val.Duration, err = r.GetI64(); err != nil {
			return fmt.Errorf("decode Buff_Duration: %w", err)
		}
		if val.Power, err = r.GetF32(); err != nil {
			return fmt.Errorf("decode Buff_Power: %w", err)
		}
		*v = val
	default:
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "Effect"}
	}
	return nil
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refActionType := ts.Reserve()
	refEffect := ts.Reserve()

	ts.Set(refActionType, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Attack", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Defense", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		types.SumTypeVariant{Name: "Heal", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
	)))

	ts.Set(refEffect, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Damage", AlgebraicType: types.AlgTypeU32()},
		types.SumTypeVariant{Name: "Buff", AlgebraicType: types.AlgTypeProduct(types.NewProductType(
			types.ProductTypeElement{Name: "duration", AlgebraicType: types.AlgTypeI64()},
			types.ProductTypeElement{Name: "power", AlgebraicType: types.AlgTypeF32()},
		))},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder([]string{"Combat"}, "ActionType", refActionType).
		WithCustomOrdering(true).Build())
	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder([]string{"Combat"}, "Effect", refEffect).
		WithCustomOrdering(true).Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
