// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/types"
)

type Item struct {
	ID          uint64
	Owner       types.Identity
	Name        string
	Description *string
	Tags        []string
	CreatedAt   types.Timestamp
	Data        []byte
}
