// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
)

func (v *Item) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	v.Owner.WriteBsatn(w)
	w.PutString(v.Name)
	if v.Description != nil {
		w.PutSumTag(0) // Some
		w.PutString(*v.Description)
	} else {
		w.PutSumTag(1) // None
	}
	w.PutArrayLen(uint32(len(v.Tags)))
	for _, elem := range v.Tags {
		w.PutString(elem)
	}
	v.CreatedAt.WriteBsatn(w)
	bsatn.WriteByteArray(w, v.Data)
}

func ReadItem(r bsatn.Reader) (*Item, error) {
	v := &Item{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Owner, err = types.ReadIdentity(r)
	if err != nil {
		return nil, err
	}
	v.Name, err = r.GetString()
	if err != nil {
		return nil, err
	}
	{
		var tag uint8
		tag, err = r.GetSumTag()
		if err != nil {
			return nil, err
		}
		if tag == 0 { // Some
			var val string
			val, err = r.GetString()
			if err != nil {
				return nil, err
			}
			v.Description = &val
		}
	}
	{
		var arrLen uint32
		arrLen, err = r.GetArrayLen()
		if err != nil {
			return nil, err
		}
		v.Tags = make([]string, arrLen)
		for i := uint32(0); i < arrLen; i++ {
			v.Tags[i], err = r.GetString()
			if err != nil {
				return nil, err
			}
		}
	}
	v.CreatedAt, err = types.ReadTimestamp(r)
	if err != nil {
		return nil, err
	}
	v.Data, err = bsatn.ReadByteArray(r)
	if err != nil {
		return nil, err
	}
	return v, nil
}
