// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type createItemArgs struct {
	Name        string
	Description *string
	Tags        []string
}

func (a *createItemArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Name)
	if a.Description != nil {
		w.PutSumTag(0) // Some
		w.PutString(*a.Description)
	} else {
		w.PutSumTag(1) // None
	}
	w.PutArrayLen(uint32(len(a.Tags)))
	for _, elem := range a.Tags {
		w.PutString(elem)
	}
}

// CallCreateItem calls the create_item reducer on the server.
func CallCreateItem(conn client.DbConnection, name string, description *string, tags []string) error {
	args := &createItemArgs{
		Name:        name,
		Description: description,
		Tags:        tags,
	}
	return conn.CallReducer("create_item", args)
}
