// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// itemTableDef implements cache.TypedTableDef for the Item table.
type itemTableDef struct{}

func (itemTableDef) TableName() string { return "Item" }

func (itemTableDef) DecodeRow(r bsatn.Reader) (*Item, error) {
	return ReadItem(r)
}

func (itemTableDef) EncodeRow(row *Item) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (itemTableDef) PrimaryKey(row *Item) uint64 {
	return row.ID
}

// ItemTable is a type-safe table cache for Item rows.
type ItemTable = cache.TypedTableCache[*Item]
