package servergen

import (
	"fmt"
	"sort"
	"strings"
)

// fileHeader returns the standard generated file header.
func fileHeader(pkgName string) string {
	return fmt.Sprintf(`// Code generated by stdb-go; DO NOT EDIT.

package %s

`, pkgName)
}

// importBlock builds an import block from unique paths.
// Imports are sorted by path for deterministic output.
func importBlock(imports map[string]string) string {
	if len(imports) == 0 {
		return ""
	}

	// Build a sorted list of (alias, path) pairs, sorted by path.
	type entry struct {
		alias, path string
	}
	entries := make([]entry, 0, len(imports))
	for alias, path := range imports {
		entries = append(entries, entry{alias, path})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].path < entries[j].path
	})

	var b strings.Builder
	b.WriteString("import (\n")
	for _, e := range entries {
		if e.alias != "" && e.alias != pathToDefaultAlias(e.path) {
			fmt.Fprintf(&b, "\t%s %q\n", e.alias, e.path)
		} else {
			fmt.Fprintf(&b, "\t%q\n", e.path)
		}
	}
	b.WriteString(")\n\n")
	return b.String()
}

// pathToDefaultAlias returns the default import alias for a package path.
func pathToDefaultAlias(path string) string {
	parts := strings.Split(path, "/")
	return parts[len(parts)-1]
}

// strPtr returns a pointer to a string.
func strPtr(s string) *string {
	return &s
}

// indent returns a string with each line indented by the given prefix.
func indent(s string, prefix string) string {
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}

// quote returns a Go string literal.
func quote(s string) string {
	return fmt.Sprintf("%q", s)
}
