// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type publicActionArgs struct {
	Name string
}

func (a *publicActionArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Name)
}

// CallPublicAction calls the public_action reducer on the server.
func CallPublicAction(conn client.DbConnection, name string) error {
	args := &publicActionArgs{
		Name: name,
	}
	return conn.CallReducer("public_action", args)
}

type privateActionArgs struct {
	Key string
}

func (a *privateActionArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Key)
}

// CallPrivateAction calls the private_action reducer on the server.
func CallPrivateAction(conn client.DbConnection, key string) error {
	args := &privateActionArgs{
		Key: key,
	}
	return conn.CallReducer("private_action", args)
}
