// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"context"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type publicQueryArgs struct {
	ID uint64
}

func (a *publicQueryArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.ID)
}

// CallPublicQuery calls the public_query procedure on the server.
func CallPublicQuery(ctx context.Context, conn client.DbConnection, id uint64) (PublicItem, error) {
	var zero PublicItem
	args := &publicQueryArgs{
		ID: id,
	}
	raw, err := conn.CallProcedure(ctx, "public_query", args)
	if err != nil {
		return zero, err
	}
	result, err := readPublicQueryResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readPublicQueryResult(r bsatn.Reader) (*PublicItem, error) {
	var result PublicItem
	var err error
	{
		var decoded *PublicItem
		decoded, err = ReadPublicItem(r)
		if err != nil {
			return nil, err
		}
		result = *decoded
	}
	_ = err
	return &result, nil
}

// CallPrivateQuery calls the private_query procedure on the server.
func CallPrivateQuery(ctx context.Context, conn client.DbConnection) (PrivateConfig, error) {
	var zero PrivateConfig
	raw, err := conn.CallProcedure(ctx, "private_query", nil)
	if err != nil {
		return zero, err
	}
	result, err := readPrivateQueryResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readPrivateQueryResult(r bsatn.Reader) (*PrivateConfig, error) {
	var result PrivateConfig
	var err error
	{
		var decoded *PrivateConfig
		decoded, err = ReadPrivateConfig(r)
		if err != nil {
			return nil, err
		}
		result = *decoded
	}
	_ = err
	return &result, nil
}
