// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *PublicItem) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutString(v.Name)
}

func ReadPublicItem(r bsatn.Reader) (*PublicItem, error) {
	v := &PublicItem{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Name, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *PrivateConfig) WriteBsatn(w bsatn.Writer) {
	w.PutString(v.Key)
	w.PutString(v.Value)
}

func ReadPrivateConfig(r bsatn.Reader) (*PrivateConfig, error) {
	v := &PrivateConfig{}
	var err error
	v.Key, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Value, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}
