// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

type publicQueryArgs struct {
	ID uint64
}

func (a *publicQueryArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.ID)
}

// CallPublicQuery calls the public_query procedure on the server.
func CallPublicQuery(conn client.DbConnection, id uint64) error {
	args := &publicQueryArgs{
		ID: id,
	}
	return conn.CallReducer("public_query", args)
}

// CallPrivateQuery calls the private_query procedure on the server.
func CallPrivateQuery(conn client.DbConnection) error {
	return conn.CallReducer("private_query", nil)
}
