// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// publicItemTableDef implements cache.TypedTableDef for the PublicItem table.
type publicItemTableDef struct{}

func (publicItemTableDef) TableName() string { return "PublicItem" }

func (publicItemTableDef) DecodeRow(r bsatn.Reader) (*PublicItem, error) {
	return ReadPublicItem(r)
}

func (publicItemTableDef) EncodeRow(row *PublicItem) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (publicItemTableDef) PrimaryKey(row *PublicItem) uint64 {
	return row.ID
}

// PublicItemTable is a type-safe table cache for PublicItem rows.
type PublicItemTable = cache.TypedTableCache[*PublicItem]

// privateConfigTableDef implements cache.TypedTableDef for the PrivateConfig table.
type privateConfigTableDef struct{}

func (privateConfigTableDef) TableName() string { return "PrivateConfig" }

func (privateConfigTableDef) DecodeRow(r bsatn.Reader) (*PrivateConfig, error) {
	return ReadPrivateConfig(r)
}

func (privateConfigTableDef) EncodeRow(row *PrivateConfig) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// PrivateConfigTable is a type-safe table cache for PrivateConfig rows.
type PrivateConfigTable = cache.TypedTableCache[*PrivateConfig]
