// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// publicViewViewDef implements cache.TypedTableDef for the PublicView view.
type publicViewViewDef struct{}

func (publicViewViewDef) TableName() string { return "PublicView" }

func (publicViewViewDef) DecodeRow(r bsatn.Reader) (*PublicView, error) {
	return ReadPublicView(r)
}

func (publicViewViewDef) EncodeRow(row *PublicView) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// PublicViewView is a type-safe view cache for PublicView rows.
type PublicViewView = cache.TypedTableCache[*PublicView]

// privateViewViewDef implements cache.TypedTableDef for the PrivateView view.
type privateViewViewDef struct{}

func (privateViewViewDef) TableName() string { return "PrivateView" }

func (privateViewViewDef) DecodeRow(r bsatn.Reader) (*PrivateView, error) {
	return ReadPrivateView(r)
}

func (privateViewViewDef) EncodeRow(row *PrivateView) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

// PrivateViewView is a type-safe view cache for PrivateView rows.
type PrivateViewView = cache.TypedTableCache[*PrivateView]
