// Code generated by stdb-gen; DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/bsatn"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/moduledef"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/reducer"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/runtime"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/server/sys"
	"github.com/clockworklabs/SpacetimeDB/sdks/go/types"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func stdbWriteShape(w bsatn.Writer, v *Shape) {
	switch val := (*v).(type) {
	case ShapeCircle:
		w.PutSumTag(0)
		w.PutF64(val.Radius)
	case ShapeRectangle:
		w.PutSumTag(1)
		w.PutF64(val.Width)
		w.PutF64(val.Height)
	case ShapePoint:
		w.PutSumTag(2)
	default:
		panic(fmt.Sprintf("stdbWriteShape: unknown variant %T", *v))
	}
}

func stdbReadShape(r bsatn.Reader, v *Shape) error {
	var err error
	var tag uint8
	if tag, err = r.GetU8(); err != nil {
		return fmt.Errorf("decode Shape tag: %w", err)
	}
	switch tag {
	case 0: // Circle
		var val ShapeCircle
		if val.Radius, err = r.GetF64(); err != nil {
			return fmt.Errorf("decode Circle: %w", err)
		}
		*v = val
	case 1: // Rectangle
		var val ShapeRectangle
		if val.Width, err = r.GetF64(); err != nil {
			return fmt.Errorf("decode Rectangle_Width: %w", err)
		}
		if val.Height, err = r.GetF64(); err != nil {
			return fmt.Errorf("decode Rectangle_Height: %w", err)
		}
		*v = val
	case 2: // Point
		var val ShapePoint
		*v = val
	default:
		return &bsatn.ErrInvalidTag{Tag: tag, SumName: "Shape"}
	}
	return nil
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refShape := ts.Reserve()

	ts.Set(refShape, types.AlgTypeSum(types.NewSumType(
		types.SumTypeVariant{Name: "Circle", AlgebraicType: types.AlgTypeF64()},
		types.SumTypeVariant{Name: "Rectangle", AlgebraicType: types.AlgTypeProduct(types.NewProductType(
			types.ProductTypeElement{Name: "width", AlgebraicType: types.AlgTypeF64()},
			types.ProductTypeElement{Name: "height", AlgebraicType: types.AlgTypeF64()},
		))},
		types.SumTypeVariant{Name: "Point", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Shape", refShape).
		WithCustomOrdering(true).Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
}
