// Code generated by stdb-go; DO NOT EDIT.

package main

import (
	"fmt"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/types"
	"go.digitalxero.dev/spacetimedb-server/moduledef"
	"go.digitalxero.dev/spacetimedb-server/reducer"
	"go.digitalxero.dev/spacetimedb-server/runtime"
	"go.digitalxero.dev/spacetimedb-server/sys"
)

// Ensure imports are used.
var (
	_ = fmt.Sprintf
	_ = bsatn.NewWriter
	_ = runtime.GlobalWriter
	_ = sys.TableIdFromName
	_ = types.NewIdentity
	_ = moduledef.NewModuleDefBuilder
	_ = reducer.NewReducerContext
)

func stdbStrPtr(s string) *string { return &s }

func StdbWritePlayer(w bsatn.Writer, v *Player) {
	w.PutU64(v.Id)
	w.PutString(v.Name)
}

func StdbReadPlayer(r bsatn.Reader, v *Player) error {
	var err error
	if v.Id, err = r.GetU64(); err != nil {
		return fmt.Errorf("decode Id: %w", err)
	}
	if v.Name, err = r.GetString(); err != nil {
		return fmt.Errorf("decode Name: %w", err)
	}
	return nil
}

func stdbCallReducer(id uint32, ctx reducer.ReducerContext, args []byte) error {
	switch id {
	default:
		return fmt.Errorf("unknown reducer id %d", id)
	}
}

func stdbCallView(id uint32, sender types.Identity, args []byte) ([]byte, error) {
	ctx := reducer.NewViewContext(sender)
	switch id {
	case 0: // get_players
		result := GetPlayers(ctx)
		w := bsatn.NewWriter(256)
		w.PutSumTag(0) // ViewResultHeader::RowData
		if result == nil {
			w.PutArrayLen(0)
		} else {
			w.PutArrayLen(uint32(len(result)))
			for i := range result {
				StdbWritePlayer(w, &result[i])
			}
		}
		return w.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown view id %d", id)
	}
}

func stdbCallViewAnon(id uint32, args []byte) ([]byte, error) {
	ctx := reducer.NewAnonymousViewContext()
	switch id {
	case 0: // get_player_by_name
		stdbReader := bsatn.NewZeroCopyReader(args)
		var name string
		{
			v, err := stdbReader.GetString()
			if err != nil {
				return nil, fmt.Errorf("decode arg 0: %w", err)
			}
			name = v
		}
		result := GetPlayerByName(ctx, name)
		w := bsatn.NewWriter(256)
		w.PutSumTag(0) // ViewResultHeader::RowData
		if result != nil {
			w.PutArrayLen(1)
			StdbWritePlayer(w, &(*result))
		} else {
			w.PutArrayLen(0)
		}
		return w.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown anon view id %d", id)
	}
}

func stdbDescribeModule() []byte {
	ts := types.NewTypespace()
	builder := moduledef.NewModuleDefBuilder()

	refPlayer := ts.Reserve()

	ts.Set(refPlayer, types.AlgTypeProduct(types.NewProductType(
		types.ProductTypeElement{Name: "id", AlgebraicType: types.AlgTypeU64()},
		types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
	)))

	builder = builder.AddTypeDef(moduledef.NewTypeDefBuilder(nil, "Player", refPlayer).
		WithCustomOrdering(true).Build())

	builder = builder.AddView(moduledef.NewViewDefBuilder("get_players").
		WithIndex(0).
		WithIsPublic(false).
		WithIsAnonymous(false).
		WithParams(types.NewProductType()).
		WithReturnType(types.AlgTypeArray(types.AlgTypeRef(refPlayer))).
		Build())

	builder = builder.AddView(moduledef.NewViewDefBuilder("get_player_by_name").
		WithIndex(0).
		WithIsPublic(false).
		WithIsAnonymous(true).
		WithParams(types.NewProductType(
			types.ProductTypeElement{Name: "name", AlgebraicType: types.AlgTypeString()},
		)).
		WithReturnType(types.AlgTypeSum(types.NewSumType(
			types.SumTypeVariant{Name: "some", AlgebraicType: types.AlgTypeRef(refPlayer)},
			types.SumTypeVariant{Name: "none", AlgebraicType: types.AlgTypeProduct(types.NewProductType())},
		))).
		Build())

	builder = builder.SetTypespace(ts)
	return bsatn.Encode(builder.Build())
}

func init() {
	runtime.SetDescribeModuleHandler(stdbDescribeModule)
	runtime.SetCallReducerHandler(stdbCallReducer)
	runtime.SetCallViewHandler(stdbCallView)
	runtime.SetCallViewAnonHandler(stdbCallViewAnon)
}
