// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// recordTableDef implements cache.TypedTableDef for the Record table.
type recordTableDef struct{}

func (recordTableDef) TableName() string { return "Record" }

func (recordTableDef) DecodeRow(r bsatn.Reader) (*Record, error) {
	return ReadRecord(r)
}

func (recordTableDef) EncodeRow(row *Record) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (recordTableDef) PrimaryKey(row *Record) uint64 {
	return row.ID
}

// RecordTable is a type-safe table cache for Record rows.
type RecordTable = cache.TypedTableCache[*Record]
