// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *Record) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutString(v.Value)
}

func ReadRecord(r bsatn.Reader) (*Record, error) {
	v := &Record{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Value, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}
