// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/client"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// ModuleBindings ties together all table and view caches for the module.
type ModuleBindings struct {
	conn   client.DbConnection
	Record *RecordTable
}

// NewModuleBindings registers all tables and views with the connection and
// returns a ModuleBindings with typed cache handles.
func NewModuleBindings(conn client.DbConnection) *ModuleBindings {
	c := conn.Cache()
	m := &ModuleBindings{conn: conn}
	m.Record = cache.RegisterTypedTableWithPK[*Record, uint64](c, recordTableDef{})
	return m
}

// Conn returns the underlying database connection.
func (m *ModuleBindings) Conn() client.DbConnection {
	return m.conn
}
