// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

// CallResetAll calls the reset_all reducer on the server.
func CallResetAll(conn client.DbConnection) error {
	return conn.CallReducer("reset_all", nil)
}

type addRecordArgs struct {
	Value string
}

func (a *addRecordArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Value)
}

// CallAddRecord calls the add_record reducer on the server.
func CallAddRecord(conn client.DbConnection, value string) error {
	args := &addRecordArgs{
		Value: value,
	}
	return conn.CallReducer("add_record", args)
}
