// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"context"
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client"
)

// CallCountUsers calls the count_users procedure on the server.
func CallCountUsers(ctx context.Context, conn client.DbConnection) (uint64, error) {
	var zero uint64
	raw, err := conn.CallProcedure(ctx, "count_users", nil)
	if err != nil {
		return zero, err
	}
	result, err := readCountUsersResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readCountUsersResult(r bsatn.Reader) (*uint64, error) {
	var result uint64
	var err error
	result, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	_ = err
	return &result, nil
}

type greetingArgs struct {
	Name string
}

func (a *greetingArgs) WriteBsatn(w bsatn.Writer) {
	w.PutString(a.Name)
}

// CallGreeting calls the greeting procedure on the server.
func CallGreeting(ctx context.Context, conn client.DbConnection, name string) (string, error) {
	var zero string
	args := &greetingArgs{
		Name: name,
	}
	raw, err := conn.CallProcedure(ctx, "greeting", args)
	if err != nil {
		return zero, err
	}
	result, err := readGreetingResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readGreetingResult(r bsatn.Reader) (*string, error) {
	var result string
	var err error
	result, err = r.GetString()
	if err != nil {
		return nil, err
	}
	_ = err
	return &result, nil
}

// CallIsReady calls the is_ready procedure on the server.
func CallIsReady(ctx context.Context, conn client.DbConnection) (bool, error) {
	var zero bool
	raw, err := conn.CallProcedure(ctx, "is_ready", nil)
	if err != nil {
		return zero, err
	}
	result, err := readIsReadyResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readIsReadyResult(r bsatn.Reader) (*bool, error) {
	var result bool
	var err error
	result, err = r.GetBool()
	if err != nil {
		return nil, err
	}
	_ = err
	return &result, nil
}

type maybeUserArgs struct {
	UserID uint64
}

func (a *maybeUserArgs) WriteBsatn(w bsatn.Writer) {
	w.PutU64(a.UserID)
}

// CallMaybeUser calls the maybe_user procedure on the server.
func CallMaybeUser(ctx context.Context, conn client.DbConnection, userID uint64) (*User, error) {
	var zero *User
	args := &maybeUserArgs{
		UserID: userID,
	}
	raw, err := conn.CallProcedure(ctx, "maybe_user", args)
	if err != nil {
		return zero, err
	}
	result, err := readMaybeUserResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readMaybeUserResult(r bsatn.Reader) (**User, error) {
	var result *User
	var err error
	{
		var tag uint8
		tag, err = r.GetSumTag()
		if err != nil {
			return nil, err
		}
		if tag == 0 { // Some
			var val User
			{
				var decoded *User
				decoded, err = ReadUser(r)
				if err != nil {
					return nil, err
				}
				val = *decoded
			}
			result = &val
		}
	}
	_ = err
	return &result, nil
}

// CallAllNames calls the all_names procedure on the server.
func CallAllNames(ctx context.Context, conn client.DbConnection) ([]string, error) {
	var zero []string
	raw, err := conn.CallProcedure(ctx, "all_names", nil)
	if err != nil {
		return zero, err
	}
	result, err := readAllNamesResult(bsatn.NewReader(raw))
	if err != nil {
		return zero, err
	}
	return *result, nil
}

func readAllNamesResult(r bsatn.Reader) (*[]string, error) {
	var result []string
	var err error
	{
		var arrLen uint32
		arrLen, err = r.GetArrayLen()
		if err != nil {
			return nil, err
		}
		result = make([]string, arrLen)
		for i := uint32(0); i < arrLen; i++ {
			result[i], err = r.GetString()
			if err != nil {
				return nil, err
			}
		}
	}
	_ = err
	return &result, nil
}

// CallDoCleanup calls the do_cleanup procedure on the server.
func CallDoCleanup(ctx context.Context, conn client.DbConnection) error {
	_, err := conn.CallProcedure(ctx, "do_cleanup", nil)
	return err
}
