// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/client"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// ModuleBindings ties together all table and view caches for the module.
type ModuleBindings struct {
	conn    client.DbConnection
	Author  *AuthorTable
	Post    *PostTable
	Comment *CommentTable
}

// NewModuleBindings registers all tables and views with the connection and
// returns a ModuleBindings with typed cache handles.
func NewModuleBindings(conn client.DbConnection) *ModuleBindings {
	c := conn.Cache()
	m := &ModuleBindings{conn: conn}
	m.Author = cache.RegisterTypedTableWithPK[*Author, uint64](c, authorTableDef{})
	m.Post = cache.RegisterTypedTableWithPK[*Post, uint64](c, postTableDef{})
	m.Comment = cache.RegisterTypedTableWithPK[*Comment, uint64](c, commentTableDef{})
	return m
}

// Conn returns the underlying database connection.
func (m *ModuleBindings) Conn() client.DbConnection {
	return m.conn
}
