// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

type Author struct {
	ID   uint64
	Name string
}

type Post struct {
	ID       uint64
	AuthorID uint64
	Title    string
	Body     string
}

type Comment struct {
	ID       uint64
	PostID   uint64
	AuthorID uint64
	Content  string
}
