// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
	"go.digitalxero.dev/spacetimedb-client/client/cache"
)

// authorTableDef implements cache.TypedTableDef for the Author table.
type authorTableDef struct{}

func (authorTableDef) TableName() string { return "Author" }

func (authorTableDef) DecodeRow(r bsatn.Reader) (*Author, error) {
	return ReadAuthor(r)
}

func (authorTableDef) EncodeRow(row *Author) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (authorTableDef) PrimaryKey(row *Author) uint64 {
	return row.ID
}

// AuthorTable is a type-safe table cache for Author rows.
type AuthorTable = cache.TypedTableCache[*Author]

// postTableDef implements cache.TypedTableDef for the Post table.
type postTableDef struct{}

func (postTableDef) TableName() string { return "Post" }

func (postTableDef) DecodeRow(r bsatn.Reader) (*Post, error) {
	return ReadPost(r)
}

func (postTableDef) EncodeRow(row *Post) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (postTableDef) PrimaryKey(row *Post) uint64 {
	return row.ID
}

// PostTable is a type-safe table cache for Post rows.
type PostTable = cache.TypedTableCache[*Post]

// commentTableDef implements cache.TypedTableDef for the Comment table.
type commentTableDef struct{}

func (commentTableDef) TableName() string { return "Comment" }

func (commentTableDef) DecodeRow(r bsatn.Reader) (*Comment, error) {
	return ReadComment(r)
}

func (commentTableDef) EncodeRow(row *Comment) []byte {
	w := bsatn.NewWriter(64)
	row.WriteBsatn(w)
	return w.Bytes()
}

func (commentTableDef) PrimaryKey(row *Comment) uint64 {
	return row.ID
}

// CommentTable is a type-safe table cache for Comment rows.
type CommentTable = cache.TypedTableCache[*Comment]
