// Code generated by stdb-go generate client; DO NOT EDIT.

package module_bindings

import (
	"go.digitalxero.dev/spacetimedb-client/bsatn"
)

func (v *Author) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutString(v.Name)
}

func ReadAuthor(r bsatn.Reader) (*Author, error) {
	v := &Author{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Name, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *Post) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutU64(v.AuthorID)
	w.PutString(v.Title)
	w.PutString(v.Body)
}

func ReadPost(r bsatn.Reader) (*Post, error) {
	v := &Post{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.AuthorID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Title, err = r.GetString()
	if err != nil {
		return nil, err
	}
	v.Body, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}

func (v *Comment) WriteBsatn(w bsatn.Writer) {
	w.PutU64(v.ID)
	w.PutU64(v.PostID)
	w.PutU64(v.AuthorID)
	w.PutString(v.Content)
}

func ReadComment(r bsatn.Reader) (*Comment, error) {
	v := &Comment{}
	var err error
	v.ID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.PostID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.AuthorID, err = r.GetU64()
	if err != nil {
		return nil, err
	}
	v.Content, err = r.GetString()
	if err != nil {
		return nil, err
	}
	return v, nil
}
